x-tier-label: &tier-label
  hy-home.tier: data

volumes:
  cassandra-node1-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_DATA_DIR}/cassandra/node1
  cassandra-exporter-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_DATA_DIR}/cassandra/exporter

services:
  cassandra-exporter:
    profiles:
      - 'data'
      - obs
    extends:
      file: ../../../common-optimizations.yml
      service: template-infra-low
    image: bitnami/cassandra-exporter:2.3.11
    container_name: cassandra-exporter
    hostname: cassandra-exporter
    read_only: true
    tmpfs:
      - /tmp
    expose:
      - ${CASSANDRA_EXPORTER_PORT:-8080}
      - ${CASSANDRA_EXPORTER_LISTEN_PORT:-8081}
    depends_on:
      cassandra-node1:
        condition: service_healthy
    networks:
      - infra_net
    volumes:
      - cassandra-exporter-volume:/opt/bitnami/cassandra-exporter/conf:rw
    command: java -jar ./cassandra_exporter.jar ./conf/config.yml
    labels:
      <<: *tier-label

  cassandra-node1:
    profiles:
      - 'data'
    extends:
      file: ../../../common-optimizations.yml
      service: template-stateful-high
    image: cassandra:5.0.6
    container_name: cassandra-node1
    hostname: cassandra-node1
    read_only: false
    expose:
      - ${CASSANDRA_INTER_NODE_PORT:-7000}
      - ${CASSANDRA_CLIENT_PORT:-9042}
    networks:
      - infra_net
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD_FILE=/run/secrets/cassandra_password
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    volumes:
      - cassandra-node1-volume:/bitnami/cassandra:rw
    secrets:
      - cassandra_password
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep -E '^UN' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    labels:
      <<: *tier-label
