{
 "title": "Airflow DAGs Overview",
 "description": "A simple dashboard to monitor Apache Airflow DAGs — track total DAGs, last run status, execution durations, and success/failure trends across instances.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "dag_id",
    "label": "DAG ID",
    "query": {
     "query": "label_values(airflow_dag_last_status, dag_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total DAGs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (dag_id) (airflow_dag_last_status))"
    }
   ]
  },
  {
   "title": "DAGs Information with Run Counts",
   "type": "table",
   "gridPos": { "h": 26, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (dag_id, instance, owner) (airflow_dag_status{dag_id=~\"$dag_id\"})"
    },
    {
     "expr": "sum by (dag_id) (airflow_dag_status{dag_id=~\"$dag_id\", status=\"success\"})",
     "legendFormat": "Total Success"
    },
    {
     "expr": "sum by (dag_id) (airflow_dag_status{dag_id=~\"$dag_id\", status=\"failed\"})",
     "legendFormat": "Total Failed"
    },
    {
     "expr": "last_over_time(airflow_dag_run_duration{dag_id=~\"$dag_id\"}[1d])"
    }
   ]
  },
  {
   "title": "DAG Last Run Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (dag_id, status) (airflow_dag_last_status{dag_id=~\"$dag_id\"}) == 1"
    }
   ]
  }
 ]
}