{
 "title": "ArgoCD / Application / Overview",
 "description": "A dashboard that monitors ArgoCD with a focus on the applications of ArgoCD. The dashboards were generated using [argo-cd-mixin](https://github.com/adinhodovic/argo-cd-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "ci/cd",
  "argo-cd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(argocd_app_info{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\"}, namespace)"
   },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "kubernetes_cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\"}, project)"
   },
   {
    "name": "application_namespace",
    "label": "Application Namespace",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\", project=~\"$project\"}, exported_namespace)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(argocd_app_info{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$kubernetes_cluster\", project=~\"$project\", exported_namespace=~\"$application_namespace\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary By Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "description": "A timeseries panel showing the health status of applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n) by (job, project, health_status)\n",
     "legendFormat": "{{ project }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "description": "A timeseries panel showing the sync status of applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n) by (job, project, sync_status)\n",
     "legendFormat": "{{ project }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Syncs",
   "type": "timeseries",
   "description": "A timeseries panel showing the sync results of applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, project, phase)\n",
     "legendFormat": "{{ project }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Application Auto Sync Enabled",
   "type": "timeseries",
   "description": "A timeseries panel showing whether auto sync is enabled for applications managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n\n  }\n) by (job, project, autosync_enabled)\n",
     "legendFormat": "{{ project }} - {{ autosync_enabled }}"
    }
   ]
  },
  {
   "title": "Applications (Unhealthy/OutOfSync/AutoSyncDisabled) Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Unhealthy Applications",
   "type": "table",
   "description": "A table listing all unhealthy applications managed by ArgoCD.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\n    health_status!~\"Healthy|Progressing\"\n  }\n) by (job, dest_server, project, name, exported_namespace, health_status) > 0\n"
    }
   ]
  },
  {
   "title": "Out Of Sync Applications",
   "type": "table",
   "description": "A table listing all unhealthy applications managed by ArgoCD.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\n    sync_status!=\"Synced\"\n  }\n) by (job, dest_server, project, name, exported_namespace, sync_status) > 0\n"
    }
   ]
  },
  {
   "title": "Applications That Failed to Sync (7d)",
   "type": "table",
   "description": "A table listing all applications that failed to sync in the last 7 days managed by ArgoCD.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\n        phase!=\"Succeeded\"\n      }[7d]\n    )\n  )\n) by (job, dest_server, project, name, exported_namespace, phase) > 0\n"
    }
   ]
  },
  {
   "title": "Applications With Auto Sync Disabled",
   "type": "table",
   "description": "A table listing all applications with auto sync disabled managed by ArgoCD.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\n    autosync_enabled!=\"true\"\n  }\n) by (job, dest_server, project, name, exported_namespace, autosync_enabled) > 0\n"
    }
   ]
  },
  { "title": "Application ($application)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "application" },
  {
   "title": "Application Health Status by Application",
   "type": "timeseries",
   "description": "A timeseries panel showing the health status of each application managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\nexported_namespace=~\"$application_namespace\",\nname=~\"$application\"\n\n  }\n) by (namespace, job, dest_server, project, name, exported_namespace, health_status)\n",
     "legendFormat": "{{ exported_namespace }}/{{ name }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status by Application",
   "type": "timeseries",
   "description": "A timeseries panel showing the sync status of each application managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\nexported_namespace=~\"$application_namespace\",\nname=~\"$application\"\n\n  }\n) by (namespace, job, dest_server, project, name, exported_namespace, sync_status)\n",
     "legendFormat": "{{ exported_namespace }}/{{ name }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Result by Application",
   "type": "timeseries",
   "description": "A timeseries panel showing the sync result of each application managed by ArgoCD.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n,\ndest_server=~\"$kubernetes_cluster\",\nproject=~\"$project\"\n,\nexported_namespace=~\"$application_namespace\",\nname=~\"$application\"\n\n      }[$__rate_interval]\n    )\n  )\n) by (namespace, job, dest_server, project, name, exported_namespace, phase)\n",
     "legendFormat": "{{ exported_namespace }}/{{ name }} - {{ phase }}"
    }
   ]
  }
 ]
}