x-tier-label: &tier-label
  hy-home.tier: data

volumes:
  db-config:

services:
  studio:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: supabase-studio
    image: supabase/studio:2025.11.10-sha-5291fe3
    restart: unless-stopped
    depends_on:
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  kong:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: supabase-kong
    image: kong:3.9.1
    tmpfs:
      - /tmp
      - /var/run/kong
    restart: unless-stopped
    ports:
      - ${SUPABASE_KONG_HTTP_HOST_PORT:-8000}:8000/tcp
      - ${SUPABASE_KONG_HTTPS_HOST_PORT:-8443}:8443/tcp
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/api/kong.yml:/home/kong/temp.yml:ro
    networks:
      - infra_net
    labels:
      <<: *tier-label

  auth:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: supabase-auth
    image: supabase/gotrue:v2.182.1
    tmpfs:
      - /tmp
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  rest:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-low
    container_name: supabase-rest
    image: postgrest/postgrest:v13.0.8
    tmpfs:
      - /tmp
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  realtime:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: realtime-dev.supabase-realtime
    image: supabase/realtime:v2.63.0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  storage:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: supabase-storage
    image: supabase/storage-api:v1.29.0
    restart: unless-stopped
    read_only: false
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/storage:/var/lib/storage
    depends_on:
      db:
        condition: service_healthy
      rest:
        condition: service_started
      imgproxy:
        condition: service_started
    networks:
      - infra_net
    labels:
      <<: *tier-label

  imgproxy:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-low
    container_name: supabase-imgproxy
    image: darthsim/imgproxy:v3.30.1
    tmpfs:
      - /tmp
    restart: unless-stopped
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/storage:/var/lib/storage
    networks:
      - infra_net
    labels:
      <<: *tier-label

  meta:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-low
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.93.1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  functions:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-high
    container_name: supabase-edge-functions
    image: supabase/edge-runtime:v1.69.23
    restart: unless-stopped
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/functions:/home/deno/functions
    depends_on:
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  analytics:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-high
    container_name: supabase-analytics
    image: supabase/logflare:1.22.6
    restart: unless-stopped
    ports:
      - ${SUPABASE_ANALYTICS_HOST_PORT:-4000}:4000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  db:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-high
    container_name: supabase-db
    image: supabase/postgres:15.14.1.068
    restart: unless-stopped
    read_only: false
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql
      - ${DEFAULT_DATA_DIR}/supabase/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql
      - ${DEFAULT_DATA_DIR}/supabase/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql
      - ${DEFAULT_DATA_DIR}/supabase/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql
      - ${DEFAULT_DATA_DIR}/supabase/db/data:/var/lib/postgresql/data
      - ${DEFAULT_DATA_DIR}/supabase/db/_supabase.sql:/docker-entrypoint-initdb.d/migrations/97-_supabase.sql
      - ${DEFAULT_DATA_DIR}/supabase/db/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql
      - ${DEFAULT_DATA_DIR}/supabase/db/pooler.sql:/docker-entrypoint-initdb.d/migrations/99-pooler.sql
      - db-config:/etc/postgresql-custom
    depends_on:
      vector:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label

  vector:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: supabase-vector
    image: timberio/vector:0.52.0-alpine
    restart: unless-stopped
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/logs/vector.yml:/etc/vector/vector.yml:ro
      - ${DOCKER_SOCKET_LOCATION:-/var/run/docker.sock}:/var/run/docker.sock:ro
    command: ['--config', '/etc/vector/vector.yml']
    networks:
      - infra_net
    labels:
      <<: *tier-label

  supavisor:
    profiles:
      - 'data'
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    container_name: supabase-pooler
    image: supabase/supavisor:2.7.4
    restart: unless-stopped
    ports:
      - ${SUPABASE_POSTGRES_HOST_PORT:-5432}:5432
      - ${SUPABASE_POOLER_PROXY_PORT_TRANSACTION_HOST_PORT:-6543}:6543
    volumes:
      - ${DEFAULT_DATA_DIR}/supabase/pooler/pooler.exs:/etc/pooler/pooler.exs:ro
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    networks:
      - infra_net
    labels:
      <<: *tier-label
