#!/usr/bin/env bash
# Generated by scripts/operations/provider_surface_renderer.py; Claude PreToolUse adapter (docker-compose-pre.sh).
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
exec bash "$PROJECT_DIR/scripts/hooks/agent-event-hook.sh" PreToolUse
