# ============================================================================
# Labeler Configuration
#
# Auto-label PRs based on changed files for hy-home.docker
# ============================================================================

# Infrastructure
"infrastructure":
  - "infra/**/*"
  - "docker-compose.yml"
  - "Dockerfile"

# Scripts & Tooling
"scripts":
  - "scripts/**/*"
  - ".agent/**/*"
  - ".cursorrules"

# Documentation
"documentation":
  - "**/*.md"
  - "docs/**/*"

# CI/CD
"ci/cd":
  - ".github/**/*"

# Security
"security":
  - "**/security/**/*"
  - "secrets/**/*"
  - ".github/SECURITY.md"
