# Infra Layer
area/infra:
  - changed-files:
      - any-glob-to-any-file: 'infra/**/*'

# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
      - any-glob-to-any-file: '*.md'

# Scripts
area/scripts:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**/*'

# GitHub & Workflow
area/github:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
