{
 "title": "Internal Kubernetes Routes",
 "description": "Monitor Routes from one Node to another",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Route Up Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_network_available{job=\"network-checker\"} == 1) / count(k8s_network_available{job=\"network-checker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "k8s_network_available{job=\"network-checker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k8s_network_available", "legendFormat": "{{from}} -> {{to}}" }
   ]
  },
  {
   "title": "Latency History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "k8s_network_latency{job=\"network-checker\"}",
     "legendFormat": "{{from}} -> {{to}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_network_latency{job=\"network-checker\"}",
     "legendFormat": "{{from}} -> {{to}}"
    }
   ]
  }
 ]
}