# Hy-Home System Optimization Templates
# This file is intended to be included in other docker-compose files to provide common anchors.

x-security-baseline: &security-baseline
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

x-logging-loki: &logging-loki
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    loki-external-labels: "job=infra,container={{.Name}}"

x-labels-base: &labels-base
  hy-home.scope: infra
  observability.logs: "true"

x-restart: &default-restart
  restart: unless-stopped

# --- Resource Presets ---
x-resource-low: &resource-low
  deploy:
    resources:
      limits:
        cpus: "0.2"
        memory: 128M
      reservations:
        memory: 64M

x-resource-med: &resource-med
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: 512M
      reservations:
        memory: 256M

x-resource-high: &resource-high
  deploy:
    resources:
      limits:
        cpus: "1.0"
        memory: 1G
      reservations:
        memory: 512M

# --- Healthcheck Templates ---
x-healthcheck-http: &healthcheck-http
  healthcheck:
    test:
      [
        "CMD",
        "wget",
        "--no-verbose",
        "--tries=1",
        "--spider",
        "http://localhost:{{.ServicePort}}/health",
      ]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
