http:
  routers:
    k3s-ingress:
      entryPoints:
        - websecure

      rule: HostRegexp(`[a-z0-9-]+\.k8s\.hy\.home\.arpa`)

      # Docker의 구체적인 Host() router보다 낮게 설정
      priority: 1

      tls: {}

      service: k3s-ingress

  services:
    k3s-ingress:
      loadBalancer:
        passHostHeader: true

        servers:
          - url: "http://192.168.0.13:32246"
