# dynamic/middleware.yml
http:
  serversTransports:
    # 'opensearch-transport'라는 이름의 규칙 생성
    opensearch-transport:
      serverName: "localhost" # [핵심] 인증서 검사 시 이 도메인으로 검증하라!
      rootCAs:
        - "/certs/rootCA.pem" # 검증에 사용할 신뢰하는 뿌리 인증서
    opensearch-dashboards-transport:
      serverName: "localhost" # [핵심] 인증서 검사 시 이 도메인으로 검증하라!
      rootCAs:
        - "/certs/rootCA.pem" # 검증에 사용할 신뢰하는 뿌리 인증서
  services:
    oauth2-proxy-svc:
      loadBalancer:
        servers:
          - url: "http://oauth2-proxy:4180"

  middlewares:
    # 1. 기존 SSO 인증 (앱 보호용)
    sso-auth:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-Request-User"
          - "X-Auth-Request-Email"
          - "Authorization"
          - "X-Auth-Request-Access-Token"
          - "X-Auth-Request-Id-Token"

    sso-errors:
      errors:
        status:
          - "401-403"
        service: oauth2-proxy-svc
        query: "/oauth2/sign_in?rd={url}"

    # 2. 대시보드용 Basic Auth (Docker Secret 기반)
    dashboard-auth:
      basicAuth:
        usersFile: "/run/secrets/traefik_basicauth_password"

    # 3. OpenSearch API용 Basic Auth (인증 성공 시 Authorization 헤더를 백엔드로 전달)
    opensearch-auth:
      basicAuth:
        removeHeader: false
        usersFile: "/run/secrets/traefik_opensearch_basicauth_password"

    req-rate-limit:
      rateLimit:
        average: 100 # 초당 평균 100개 요청
        burst: 50 # 최대 50개까지 버스트 허용
        sourceCriterion:
          requestHost: true
