FROM quay.io/debezium/connect:3.6.3.Final AS debezium

FROM confluentinc/cp-kafka-connect:8.3.2

USER root

COPY --from=debezium \
    /kafka/connect/debezium-connector-postgres \
    /usr/share/confluent-hub-components/debezium-connector-postgres

USER appuser
