x-tier-label: &tier-label
  hy-home.tier: tooling


volumes:
  k6-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_TOOLING_DIR}/k6

services:
  k6-master:
    profiles:
      - 'tooling'
      - testing
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    build: .
    read_only: false
    labels:
      <<: *tier-label
    ports:
      - '${LOCUST_HOST_PORT:-18089}:${LOCUST_PORT:-8089}'
    volumes:
      - k6-data:/mnt/locust:rw
    networks:
      - infra_net
    command: locust -f /mnt/locust/locustfile.py --master
    healthcheck:
      test: ['CMD', 'wget', '-q', '-O', '/dev/null', 'http://localhost:8089']
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - '${DEFAULT_URL:-localhost}:host-gateway'
