x-tier-label: &tier-label
  hy-home.tier: security

volumes:
  vault-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_SECURITY_DIR}/vault

services:
  vault:
    profiles:
      - core
    extends:
      file: ../../common-optimizations.yml
      service: template-stateful-med
    image: hashicorp/vault:1.21.2
    container_name: vault
    restart: unless-stopped
    ports:
      - '${VAULT_HOST_PORT:-8200}:${VAULT_PORT:-8200}'
    expose:
      - ${VAULT_PORT:-8200}
    environment:
      VAULT_ADDR: 'http://0.0.0.0:${VAULT_PORT:-8200}'
      VAULT_API_ADDR: 'http://0.0.0.0:${VAULT_PORT:-8200}'
    volumes:
      - vault-data:/vault/file:rw
      - ./config:/vault/config:ro
    command: vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    networks:
      - infra_net
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -fsS "http://localhost:${VAULT_PORT:-8200}/v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200" || wget -q --spider "http://localhost:${VAULT_PORT:-8200}/v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200" || exit 1',
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    labels:
      <<: *tier-label
      traefik.enable: 'true'
      traefik.http.routers.vault.rule: Host(`vault.${DEFAULT_URL}`)
      traefik.http.routers.vault.entrypoints: websecure
      traefik.http.routers.vault.tls: 'true'
      traefik.http.services.vault.loadbalancer.server.port: ${VAULT_PORT:-8200}
