x-tier-label: &tier-label
  hy-home.tier: messaging

volumes:
  rabbitmq-data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DEFAULT_MESSAGE_BROKER_DIR}/rabbitmq

services:
  rabbitmq:
    profiles:
      - 'messaging-option'
    extends:
      file: ../../common-optimizations.yml
      service: template-stateful-med
    image: rabbitmq:4.2.5-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    read_only: false
    ports:
      - '${RABBITMQ_HOST_PORT:-5672}:${RABBITMQ_PORT:-5672}'
      - '${RABBITMQ_MANAGEMENT_HOST_PORT:-15672}:${RABBITMQ_MANAGEMENT_PORT:-15672}'
    secrets:
      - rabbitmq_user
      - rabbitmq_password
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    volumes:
      - rabbitmq-data-volume:/var/lib/rabbitmq:rw
    networks:
      infra_net:
        ipv4_address: 172.19.0.200
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'check_running']
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
    labels:
      <<: *tier-label
      traefik.enable: 'true'
      traefik.http.routers.rabbitmq.rule: Host(`rabbitmq.${DEFAULT_URL}`)
      traefik.http.routers.rabbitmq.entrypoints: websecure
      traefik.http.routers.rabbitmq.tls: 'true'
      traefik.http.routers.rabbitmq.middlewares: gateway-standard-chain@file,sso-errors@file,sso-auth@file
      traefik.http.services.rabbitmq.loadbalancer.server.port: ${RABBITMQ_MANAGEMENT_PORT:-15672}
