#!/usr/bin/env bash
# Classify changed authored files into the obligations that decide which checks
# apply, and name the generated files no formatter may touch.
#
# The skill body used to ask a caller to do this by reading paths, which made
# the answer depend on who was looking. The classification is mechanical, so it
# is fixed here and the body interprets the output instead.
#
# Usage: classify-changed-files.sh [--base <ref>]
#   --base   compare against this ref instead of the staged index.
set -euo pipefail

fail() { printf 'classification failed: %s\n' "$1" >&2; exit 2; }
usage() { printf '%s\n' 'Usage: classify-changed-files.sh [--base <ref> | --help | -h]'; }

base=""
case "$#" in
  0) ;;
  1) case "$1" in -h|--help) usage; exit 0 ;; *) fail invalid-arguments ;; esac ;;
  2) [[ "$1" == --base && -n "$2" && "$2" != -* ]] || fail invalid-arguments
     base="$2" ;;
  *) fail invalid-arguments ;;
esac

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)" || fail script-root
root="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null)" || fail git-root
[[ -n "$root" && -d "$root" ]] || fail git-root
args=(diff --name-only -z --diff-filter=ACMR)
if [[ -n "$base" ]]; then
  args+=("$base"...HEAD --)
else
  args+=(--cached --)
fi
mapfile -d '' -t changed < <(git -C "$root" "${args[@]}" 2>/dev/null)
discovery_pid=$!
wait "$discovery_pid" || fail git-diff

emit() { printf '%s=%s\n' "$1" "$2"; }
list() {
  local label="$1"; shift
  printf '%s_count=%d\n' "$label" "$#"
  for item in "$@"; do printf '%s: %q\n' "$label" "$item"; done
}

markdown=() shell=() python=() yaml=() json=() generated=() other=()
marker='(<!--|#)[[:space:]]*generated by '
for path in "${changed[@]}"; do
  remaining="$path"
  current="$root"
  while :; do
    component="${remaining%%/*}"
    [[ -n "$component" && "$component" != . && "$component" != .. ]] || fail unsafe-path
    current+="/$component"
    [[ ! -L "$current" ]] || fail unsafe-path
    [[ "$remaining" == */* ]] || break
    remaining="${remaining#*/}"
  done
  [[ -f "$current" ]] || fail marker-input
  # A generated file is owned by its generator. Reporting it separately is the
  # point: a formatter that rewrites one produces a diff its owner did not make.
  # The marker sits after frontmatter in every generated surface here, so a
  # five-line window misses it. Twenty covers frontmatter plus the marker while
  # still refusing to read whole files.
  # Consume the full window: -q can SIGPIPE head, and shell variables lose NULs.
  if head -n 20 -- "$current" 2>/dev/null | grep -aiE "$marker" >/dev/null 2>&1; then
    generated+=("$path"); continue
  else
    marker_status=("${PIPESTATUS[@]}")
    [[ "${marker_status[0]}" == 0 ]] || fail marker-read
    [[ "${marker_status[1]}" == 1 ]] || fail marker-match
  fi
  case "$path" in
    *.md) markdown+=("$path") ;;
    *.sh|*.bash) shell+=("$path") ;;
    *.py) python+=("$path") ;;
    *.yml|*.yaml) yaml+=("$path") ;;
    *.json) json+=("$path") ;;
    *) other+=("$path") ;;
  esac
done

emit changed_total "${#changed[@]}"
list markdown "${markdown[@]}"
list shell "${shell[@]}"
list python "${python[@]}"
list yaml "${yaml[@]}"
list json "${json[@]}"
list generated "${generated[@]}"
list other "${other[@]}"
