#!/usr/bin/env bash
# Classify changed authored files into the obligations that decide which checks
# apply, and name the generated files no formatter may touch.
#
# The skill body used to ask a caller to do this by reading paths, which made
# the answer depend on who was looking. The classification is mechanical, so it
# is fixed here and the body interprets the output instead.
#
# Usage: classify-changed-files.sh [--base <ref>]
#   --base   compare against this ref instead of the staged index.
set -euo pipefail

base=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --base) base="${2:?--base needs a ref}"; shift 2 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ -n "$base" ]]; then
  mapfile -t changed < <(git diff --name-only --diff-filter=ACMR "$base"...HEAD)
else
  mapfile -t changed < <(git diff --cached --name-only --diff-filter=ACMR)
fi

emit() { printf '%s=%s\n' "$1" "$2"; }
list() {
  local label="$1"; shift
  printf '%s_count=%d\n' "$label" "$#"
  for item in "$@"; do printf '%s: %s\n' "$label" "$item"; done
}

markdown=() shell=() python=() yaml=() json=() generated=() other=()
for path in "${changed[@]}"; do
  [[ -n "$path" ]] || continue
  # A generated file is owned by its generator. Reporting it separately is the
  # point: a formatter that rewrites one produces a diff its owner did not make.
  # The marker sits after frontmatter in every generated surface here, so a
  # five-line window misses it. Twenty covers frontmatter plus the marker while
  # still refusing to read whole files.
  if head -n 20 -- "$path" 2>/dev/null | grep -qiE '(<!--|#)[[:space:]]*Generated by '; then
    generated+=("$path"); continue
  fi
  case "$path" in
    *.md) markdown+=("$path") ;;
    *.sh|*.bash) shell+=("$path") ;;
    *.py) python+=("$path") ;;
    *.yml|*.yaml) yaml+=("$path") ;;
    *.json) json+=("$path") ;;
    *) other+=("$path") ;;
  esac
done

emit changed_total "${#changed[@]}"
list markdown "${markdown[@]}"
list shell "${shell[@]}"
list python "${python[@]}"
list yaml "${yaml[@]}"
list json "${json[@]}"
list generated "${generated[@]}"
list other "${other[@]}"
