{
 "title": "OpenSearch / Node",
 "description": "Source: monitoring-mixins opensearch/opensearch-node-overview.json (2026-06-11). Provisioned by hy-home (SPEC-0193).",
 "tags": [
  "hy-home",
  "opensearch-mixin"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opensearch_os_cpu_percent{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(opensearch_os_cpu_percent{job=~\"$job\"}, cluster)"
   },
   {
    "name": "opensearch_cluster",
    "label": "Opensearch_cluster",
    "query": "label_values(opensearch_os_cpu_percent{job=~\"$job\",cluster=~\"$cluster\"}, opensearch_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(opensearch_os_cpu_percent{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "node",
    "query": "label_values(opensearch_os_cpu_percent{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\"}, node)"
   }
  ]
 },
 "panels": [
  { "title": "Node health", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "description": "CPU usage percentage of the node's Operating System.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_cpu_percent{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "description": "Memory usage percentage of the node for the operating system and OpenSearch",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_mem_used_percent{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node I/O",
   "type": "timeseries",
   "description": "Node file system read and write data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  rate(opensearch_fs_io_total_read_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__rate_interval])\n)",
     "legendFormat": "{{node}} - read"
    },
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  rate(opensearch_fs_io_total_write_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__rate_interval])\n)",
     "legendFormat": "{{node}} - write"
    }
   ]
  },
  {
   "title": "Node open connections",
   "type": "timeseries",
   "description": "Number of open connections for the selected node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_transport_server_open_number{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node disk usage",
   "type": "timeseries",
   "description": "Disk usage percentage of the selected node.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * opensearch_fs_path_free_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"} / clamp_min(opensearch_fs_path_total_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}, 1))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory swap",
   "type": "timeseries",
   "description": "Percentage of swap space used by OpenSearch and the operating system on the selected node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * opensearch_os_swap_used_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"} / clamp_min((opensearch_os_swap_used_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"} + opensearch_os_swap_free_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}), 1)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node network traffic",
   "type": "timeseries",
   "description": "Network traffic on the node's operating system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "\n  sum by (job,cluster,opensearch_cluster,instance,node) (\n  rate(opensearch_transport_rx_bytes_count{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__rate_interval])\n)\n * 8",
     "legendFormat": "{{node}} - received"
    },
    {
     "expr": "\n  sum by (job,cluster,opensearch_cluster,instance,node) (\n  rate(opensearch_transport_tx_bytes_count{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__rate_interval])\n)\n * 8",
     "legendFormat": "{{node}} - sent"
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "timeseries",
   "description": "Circuit breakers tripped on the selected node by type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "trips" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  increase(opensearch_circuitbreaker_tripped_count{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{node}} - {{ name }}"
    }
   ]
  },
  { "title": "Node Roles", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "Roles timeline",
   "type": "status-history",
   "description": "OpenSearch node roles over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "\n  max by (job,cluster,opensearch_cluster,instance,node,role) (\n  max_over_time(opensearch_node_role_bool{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\", role=\"data\"}[1m]) == 1\n)\n * 2",
     "legendFormat": "{{ node }} / data"
    },
    {
     "expr": "\n  max by (job,cluster,opensearch_cluster,instance,node,role) (\n  max_over_time(opensearch_node_role_bool{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\", role=\"master\"}[1m]) == 1\n)\n * 3",
     "legendFormat": "{{ node }} / master"
    },
    {
     "expr": "\n  max by (job,cluster,opensearch_cluster,instance,node,role) (\n  max_over_time(opensearch_node_role_bool{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\", role=\"ingest\"}[1m]) == 1\n)\n * 4",
     "legendFormat": "{{ node }} / ingest"
    },
    {
     "expr": "\n  max by (job,cluster,opensearch_cluster,instance,node,role) (\n  max_over_time(opensearch_node_role_bool{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\", role=\"cluster_manager\"}[1m]) == 1\n)\n * 5",
     "legendFormat": "{{ node }} / cluster_manager"
    },
    {
     "expr": "\n  max by (job,cluster,opensearch_cluster,instance,node,role) (\n  max_over_time(opensearch_node_role_bool{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\", role=\"remote_cluster_client\"}[1m]) == 1\n)\n * 6",
     "legendFormat": "{{ node }} / remote_client"
    }
   ]
  },
  { "title": "Node JVM", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 42 } },
  {
   "title": "JVM heap used vs committed",
   "type": "timeseries",
   "description": "JVM heap memory usage vs committed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_jvm_mem_heap_used_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: JVM heap used"
    },
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_jvm_mem_heap_committed_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: JVM heap committed"
    }
   ]
  },
  {
   "title": "JVM non-heap used vs committed",
   "type": "timeseries",
   "description": "JVM non-heap memory usage vs committed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_jvm_mem_nonheap_used_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: JVM non-heap used"
    },
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_jvm_mem_nonheap_committed_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: JVM non-heap committed"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "JVM thread count.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_jvm_threads_number{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: JVM threads"
    }
   ]
  },
  {
   "title": "JVM buffer pools",
   "type": "timeseries",
   "description": "JVM buffer pool usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node,bufferpool) (\n  opensearch_jvm_bufferpool_number{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{ node }} - {{ bufferpool }}"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "timeseries",
   "description": "JVM uptime in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_jvm_uptime_seconds{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: JVM uptime"
    }
   ]
  },
  {
   "title": "JVM garbage collections",
   "type": "timeseries",
   "description": "JVM garbage collection count.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "collections" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  increase(opensearch_jvm_gc_collection_count{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{node}}: JVM GC collections"
    }
   ]
  },
  {
   "title": "JVM garbage collection time",
   "type": "timeseries",
   "description": "JVM garbage collection time in milliseconds.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  increase(opensearch_jvm_gc_collection_time_seconds{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{node}}: JVM GC time"
    }
   ]
  },
  {
   "title": "JVM buffer pool usage",
   "type": "timeseries",
   "description": "JVM buffer pool usage by pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "100 * (sum by (job,cluster,opensearch_cluster,instance,node,bufferpool) (opensearch_jvm_bufferpool_used_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"})) / clamp_min((sum by (job,cluster,opensearch_cluster,instance,node,bufferpool) (opensearch_jvm_bufferpool_total_capacity_bytes{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"})),1)",
     "legendFormat": "{{ node }} - {{ bufferpool }}"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 67 } },
  {
   "title": "Thread pool threads",
   "type": "timeseries",
   "description": "Thread pool thread count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_threadpool_threads_number{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: Threadpool threads"
    }
   ]
  },
  {
   "title": "Thread pool tasks",
   "type": "timeseries",
   "description": "Thread pool task count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,opensearch_cluster,instance,node) (\n  opensearch_threadpool_tasks_number{job=~\"$job\",cluster=~\"$cluster\",opensearch_cluster=~\"$opensearch_cluster\",instance=~\"$instance\",node=~\"$node\"}\n)",
     "legendFormat": "{{node}}: Threadpool tasks"
    }
   ]
  }
 ]
}