{
 "title": "ValKey 监控总览",
 "description": "redis_exporter for valkey",
 "tags": [
  "ValKey",
  "Redis",
  "Prometheus",
  "reepu.com"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "集群", "query": { "query": "label_values(redis_up, job)" } },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values({job=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "每秒操作数 [1分钟]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(redis_commands_processed_total{instance=\"$instance\"}[1m])/60"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "接收"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "已用内存"
    },
    {
     "expr": "redis_memory_used_peak_bytes{instance=\"$instance\"}",
     "legendFormat": "使用峰值"
    },
    {
     "expr": "redis_memory_used_lua_bytes{instance=\"$instance\"}",
     "legendFormat": "Lua引擎内存"
    },
    {
     "expr": "redis_memory_used_dataset_bytes{instance=\"$instance\"}",
     "legendFormat": "数据集内存"
    },
    {
     "expr": "redis_memory_used_overhead_bytes{instance=\"$instance\"}",
     "legendFormat": "内存开销"
    },
    {
     "expr": "redis_memory_used_rss_bytes{instance=\"$instance\"}",
     "legendFormat": "RSS 内存"
    }
   ]
  },
  {
   "title": "运行时长",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "角色",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "已连接客户端数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "版本",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{redis_version}}"
    }
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Key 总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "keys",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{instance=\"$instance\"}[3m])",
     "legendFormat": "过期键数"
    },
    {
     "expr": "rate(redis_evicted_keys_total{instance=\"$instance\"}[3m])",
     "legendFormat": "驱逐键数"
    }
   ]
  },
  {
   "title": "keys",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_keyspace_hits_total{instance=\"$instance\"}",
     "legendFormat": "命中次数"
    },
    {
     "expr": "redis_keyspace_misses_total{instance=\"$instance\"}",
     "legendFormat": "未命中次数"
    }
   ]
  },
  {
   "title": "内存淘汰策略",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{maxmemory_policy}}"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (rate(redis_cpu_sys_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_sys_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "系统"
    },
    {
     "expr": "100 * (rate(redis_cpu_user_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_user_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "用户"
    }
   ]
  },
  {
   "title": "磁盘每秒读写次数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=\"$instance\"} [5m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "网络吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "入流量"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "出流量"
    }
   ]
  },
  {
   "title": "每秒连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_connections_received_total{instance=\"$instance\"}[5m]) ",
     "legendFormat": "入流量"
    }
   ]
  },
  {
   "title": "数据库键数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_db_keys{instance=\"$instance\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "平均生存时间",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_db_avg_ttl_seconds{instance='$instance'}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "过期/驱逐键数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{instance=\"$instance\"}[5m])",
     "legendFormat": "过期"
    },
    {
     "expr": "rate(redis_evicted_keys_total{instance=\"$instance\"}[5m])",
     "legendFormat": "驱逐"
    }
   ]
  },
  {
   "title": "命中率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])   / (rate(redis_keyspace_misses_total{instance=\"$instance\"}[5m]) + rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])) ",
     "legendFormat": "命中"
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "已连接客户端数"
    },
    {
     "expr": "redis_config_maxclients{instance=\"$instance\"}",
     "legendFormat": "最大并发连接数"
    }
   ]
  },
  {
   "title": "阻塞与拒绝的客户端",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "redis_blocked_clients{instance=\"$instance\"}",
     "legendFormat": "阻塞客户端数"
    },
    {
     "expr": "rate(redis_rejected_connections_total{instance=\"$instance\"}[5m])",
     "legendFormat": "被拒绝的连接数"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=\"$instance\"}[5m])) / sum(rate(redis_commands_processed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "响应时间"
    }
   ]
  },
  {
   "title": "慢查询日志增量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "rate(redis_slowlog_length{instance=\"$instance\"}[5m])",
     "legendFormat": "响应时间"
    }
   ]
  }
 ]
}