from __future__ import annotations

import importlib.util
import os
import pathlib
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


ROOT = pathlib.Path(__file__).resolve().parents[2]
RENDERER = ROOT / "scripts/operations/provider_surface_renderer.py"
WRAPPER = ROOT / "scripts/operations/sync-provider-surfaces.sh"
MARKER = "Generated by scripts/operations/provider_surface_renderer.py"


def load_renderer():
    spec = importlib.util.spec_from_file_location("provider_surface_renderer", RENDERER)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load renderer: {RENDERER}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def copy_stage00(root: pathlib.Path) -> None:
    shutil.copytree(
        ROOT / "docs/00.agent-governance",
        root / "docs/00.agent-governance",
        dirs_exist_ok=True,
    )
    spec_source = (
        ROOT / "docs/03.specs/132-agent-governance-harness-convergence/spec.md"
    )
    spec_target = root / spec_source.relative_to(ROOT)
    spec_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(spec_source, spec_target)


def generated_surface(function_id: str = "retired") -> str:
    return (
        "---\n"
        f"name: {function_id}\n"
        f"description: Canonical common function for {function_id}; "
        "owned by eval-engineer.\n"
        "---\n\n"
        f"<!-- {MARKER}; source: docs/00.agent-governance/agents/functions/"
        f"{function_id}.md -->\n\n"
        "# Generated surface\n"
    )


class ProviderSurfaceRendererTests(unittest.TestCase):
    def test_catalog_load_and_render_are_deterministic_stage00_only(self) -> None:
        renderer = load_renderer()
        catalog = renderer.load_catalog(ROOT)
        self.assertEqual(14, len(catalog.agents))
        self.assertEqual(22, len(catalog.functions))
        self.assertEqual(
            sorted(record.agent_id for record in catalog.agents),
            [record.agent_id for record in catalog.agents],
        )
        self.assertEqual(
            sorted(record.function_id for record in catalog.functions),
            [record.function_id for record in catalog.functions],
        )

        function = next(
            record
            for record in catalog.functions
            if record.function_id == "code-reviewer"
        )
        first = renderer.render_function("claude", function)
        second = renderer.render_function("claude", function)
        self.assertEqual(first, second)
        self.assertIn(
            b"Generated by scripts/operations/provider_surface_renderer.py", first
        )
        self.assertIn(
            b"docs/00.agent-governance/agents/functions/code-reviewer.md", first
        )

        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_stage00(root)
            before = renderer.expected_projection(root, "claude")
            local_override = root / ".claude/skills/code-reviewer/SKILL.md"
            local_override.parent.mkdir(parents=True, exist_ok=True)
            local_override.write_text(
                "provider-local policy must not be input\n", encoding="utf-8"
            )
            after = renderer.expected_projection(root, "claude")
            self.assertEqual(before, after)

    def test_check_is_read_only_and_write_is_idempotent_with_bounded_stale_cleanup(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_stage00(root)

            legacy = root / ".claude/skills/code-reviewer/skill.md"
            legacy.parent.mkdir(parents=True, exist_ok=True)
            legacy.write_text("legacy lowercase entrypoint\n", encoding="utf-8")
            codex_legacy = root / ".codex/skills/code-reviewer/skill.md"
            codex_legacy.parent.mkdir(parents=True, exist_ok=True)
            codex_legacy.write_text("obsolete codex skill\n", encoding="utf-8")
            managed_stale = root / ".agents/skills/retired/SKILL.md"
            managed_stale.parent.mkdir(parents=True, exist_ok=True)
            managed_stale.write_text(generated_surface(), encoding="utf-8")
            check = subprocess.run(
                [sys.executable, str(RENDERER), "--root", str(root), "--check"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(1, check.returncode)
            self.assertIn("projection drift", check.stderr)
            self.assertTrue(legacy.is_file())
            self.assertFalse((root / ".claude/skills/code-reviewer/SKILL.md").exists())

            write = subprocess.run(
                [sys.executable, str(RENDERER), "--root", str(root), "--write"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(0, write.returncode, write.stdout + write.stderr)
            self.assertFalse(legacy.exists())
            self.assertFalse(codex_legacy.exists())
            self.assertFalse((root / ".codex/skills").exists())
            self.assertFalse(managed_stale.exists())
            self.assertEqual(
                22, len(list((root / ".claude/skills").glob("*/SKILL.md")))
            )
            self.assertEqual(
                22, len(list((root / ".agents/skills").glob("*/SKILL.md")))
            )

            snapshot = {
                path.relative_to(root).as_posix(): path.read_bytes()
                for path in root.rglob("*")
                if path.is_file()
            }
            second_write = subprocess.run(
                [sys.executable, str(RENDERER), "--root", str(root), "--write"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(0, second_write.returncode)
            self.assertEqual(
                snapshot,
                {
                    path.relative_to(root).as_posix(): path.read_bytes()
                    for path in root.rglob("*")
                    if path.is_file()
                },
            )

            for _ in range(2):
                clean = subprocess.run(
                    [sys.executable, str(RENDERER), "--root", str(root), "--check"],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(0, clean.returncode, clean.stdout + clean.stderr)
                self.assertIn("provider_surface_renderer: PASS", clean.stdout)

    def test_write_rejects_symlinked_managed_parent_without_external_writes(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory) / "root"
            outside = pathlib.Path(directory) / "outside"
            root.mkdir()
            outside.mkdir()
            copy_stage00(root)
            (root / ".claude").mkdir()
            (root / ".claude/skills").symlink_to(outside, target_is_directory=True)

            with self.assertRaises((OSError, ValueError)):
                renderer.write_projection(root, "claude")
            self.assertEqual([], list(outside.iterdir()))

    def test_check_reports_symlinked_output_as_unsafe_without_following_it(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory) / "root"
            outside = pathlib.Path(directory) / "outside-sentinel"
            root.mkdir()
            copy_stage00(root)
            renderer.write_projection(root, "claude")
            target = root / ".claude/skills/code-reviewer/SKILL.md"
            target.unlink()
            outside.write_text("outside provider-local payload\n", encoding="utf-8")
            target.symlink_to(outside)

            findings = renderer.find_projection_drift(root, "claude")
            matching = [
                finding
                for finding in findings
                if finding.path == target.relative_to(root)
            ]
            self.assertEqual(["unsafe"], [finding.kind for finding in matching])

            stale = root / ".agents/skills/retired/SKILL.md"
            stale.parent.mkdir(parents=True, exist_ok=True)
            stale.symlink_to(outside)
            with self.assertRaises(ValueError):
                renderer.find_managed_stale_files(root, {})

    def test_confined_write_cleans_temporary_file_after_write_failure(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            target = pathlib.Path(".claude/skills/code-reviewer/SKILL.md")
            with mock.patch.object(
                renderer.os, "write", side_effect=OSError("injected")
            ):
                with self.assertRaises(OSError):
                    renderer._write_confined(root, target, b"content")
            self.assertFalse((root / target).exists())
            self.assertEqual(
                [], list((root / target.parent).glob(f".{target.name}.tmp-*"))
            )

    def test_unknown_flags_fail_closed(self) -> None:
        result = subprocess.run(
            [sys.executable, str(RENDERER), "--check", "--unknown"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(2, result.returncode)
        self.assertIn("unrecognized arguments", result.stderr)

    def test_exact_generated_marker_does_not_treat_an_ordinary_mention_as_owned(
        self,
    ) -> None:
        renderer = load_renderer()
        exact = generated_surface().encode()
        self.assertTrue(renderer._has_exact_generated_marker(exact))
        for unowned in (
            f"This guide mentions {MARKER}.\n".encode(),
            f"<!-- prefix {MARKER}; source: docs/00.agent-governance/agents/functions/retired.md -->\n".encode(),
            f"<!-- {MARKER}; source: retired -->\n".encode(),
            f"<!-- {MARKER}; source: docs/00.agent-governance/agents/functions/retired.md --> suffix\n".encode(),
            (
                "```html\n"
                f"<!-- {MARKER}; source: "
                "docs/00.agent-governance/agents/functions/retired.md -->\n"
                "```\n"
            ).encode(),
        ):
            with self.subTest(unowned=unowned):
                self.assertFalse(renderer._has_exact_generated_marker(unowned))

    def test_marker_cleanup_restores_unowned_replacement_after_discovery(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            relative = pathlib.Path(".agents/skills/retired/SKILL.md")
            target = root / relative
            target.parent.mkdir(parents=True)
            target.write_text(generated_surface(), encoding="utf-8")
            self.assertIn(relative, renderer.find_managed_stale_files(root, {}))

            replacement = b"user-authored replacement after discovery\n"
            target.write_bytes(replacement)
            with self.assertRaises(ValueError):
                renderer._remove_stale_confined(root, relative, require_marker=True)

            self.assertEqual(replacement, target.read_bytes())
            self.assertEqual([], list(target.parent.glob(".SKILL.md.quarantine-*")))

    def test_marker_cleanup_preserves_quarantine_when_restore_would_overwrite(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            relative = pathlib.Path(".agents/skills/retired/SKILL.md")
            target = root / relative
            target.parent.mkdir(parents=True)
            original = b"unowned captured payload\n"
            target.write_bytes(original)

            def collide(_content: bytes) -> bool:
                target.write_bytes(b"concurrent replacement\n")
                return False

            with mock.patch.object(
                renderer, "_has_exact_generated_marker", side_effect=collide
            ):
                with self.assertRaises(ValueError):
                    renderer._remove_stale_confined(root, relative, require_marker=True)

            self.assertEqual(b"concurrent replacement\n", target.read_bytes())
            quarantines = list(target.parent.glob(".SKILL.md.quarantine-*"))
            self.assertEqual(1, len(quarantines))
            self.assertEqual(original, quarantines[0].read_bytes())

    def test_marker_cleanup_rejects_symlink_and_fifo_without_outside_writes(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory) / "root"
            outside = pathlib.Path(directory) / "outside"
            root.mkdir()
            outside.write_bytes(b"outside sentinel\n")
            parent = root / ".agents/skills/retired"
            parent.mkdir(parents=True)
            relative = pathlib.Path(".agents/skills/retired/SKILL.md")
            target = root / relative
            target.symlink_to(outside)

            with self.assertRaises(ValueError):
                renderer._remove_stale_confined(root, relative, require_marker=True)
            self.assertTrue(target.is_symlink())
            self.assertEqual(b"outside sentinel\n", outside.read_bytes())
            self.assertEqual([], list(parent.glob(".SKILL.md.quarantine-*")))

            target.unlink()
            os.mkfifo(target)
            with self.assertRaises(ValueError):
                renderer._remove_stale_confined(root, relative, require_marker=True)
            self.assertTrue(stat.S_ISFIFO(target.lstat().st_mode))
            self.assertEqual([], list(parent.glob(".SKILL.md.quarantine-*")))

    def test_marker_cleanup_deletes_owned_capture_and_cleans_quarantine(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            relative = pathlib.Path(".agents/skills/retired/SKILL.md")
            target = root / relative
            target.parent.mkdir(parents=True)
            target.write_text(generated_surface(), encoding="utf-8")
            renderer._remove_stale_confined(root, relative, require_marker=True)
            self.assertFalse(target.exists())
            self.assertEqual([], list(target.parent.glob(".SKILL.md.quarantine-*")))

    def test_rendered_relative_links_resolve_for_all_shared_skill_projections(
        self,
    ) -> None:
        renderer = load_renderer()
        inline_link = re.compile(rb"!?\[[^\]]*\]\(([^)\s]+)(?:\s+[^)]*)?\)")
        checked = 0
        for provider in ("claude", "agents-md"):
            projection = renderer.expected_projection(ROOT, provider)
            self.assertEqual(22, len(projection))
            for output_path, content in projection.items():
                checked += 1
                for match in inline_link.finditer(content):
                    target = match.group(1).decode()
                    if target.startswith(("#", "/", "https://", "http://", "mailto:")):
                        continue
                    target_path = target.split("#", 1)[0].split("?", 1)[0]
                    resolved = (ROOT / output_path.parent / target_path).resolve()
                    self.assertTrue(
                        resolved.is_file(),
                        f"broken projection link: {output_path} -> {target}",
                    )
                    self.assertTrue(resolved.is_relative_to(ROOT.resolve()))
        self.assertEqual(44, checked)

    def test_link_rebasing_preserves_external_absolute_and_anchor_targets(self) -> None:
        renderer = load_renderer()
        body = (
            "[relative](../agents/code-reviewer.md)\n"
            "[anchor](#procedure)\n"
            "[absolute](/docs/README.md)\n"
            "[external](https://example.com/docs)\n"
            "[mail](mailto:owner@example.com)\n"
        )
        rebased = renderer._rebase_markdown_links(
            body,
            pathlib.PurePosixPath(
                "docs/00.agent-governance/agents/functions/code-reviewer.md"
            ),
            pathlib.PurePosixPath(".claude/skills/code-reviewer/SKILL.md"),
        )
        self.assertIn(
            "[relative](../../../docs/00.agent-governance/agents/agents/code-reviewer.md)",
            rebased,
        )
        for unchanged in (
            "[anchor](#procedure)",
            "[absolute](/docs/README.md)",
            "[external](https://example.com/docs)",
            "[mail](mailto:owner@example.com)",
        ):
            self.assertIn(unchanged, rebased)

    def test_codex_skills_root_is_exactly_absent_and_empty_root_is_removed(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_stage00(root)
            skills = root / ".codex/skills"
            skills.mkdir(parents=True)

            self.assertEqual(
                [renderer.Finding(pathlib.Path(".codex/skills"), "stale")],
                renderer.find_projection_drift(root, "codex"),
            )
            renderer.write_projection(root, "codex")
            self.assertFalse(skills.exists())
            self.assertEqual([], renderer.find_projection_drift(root, "codex"))

    def test_codex_skills_root_rejects_symlink_non_directory_and_unknown_content(
        self,
    ) -> None:
        renderer = load_renderer()
        cases = ("symlink", "file", "nonempty")
        for case in cases:
            with self.subTest(case=case), tempfile.TemporaryDirectory() as directory:
                root = pathlib.Path(directory) / "root"
                outside = pathlib.Path(directory) / "outside"
                root.mkdir()
                outside.mkdir()
                copy_stage00(root)
                codex = root / ".codex"
                codex.mkdir()
                skills = codex / "skills"
                if case == "symlink":
                    skills.symlink_to(outside, target_is_directory=True)
                elif case == "file":
                    skills.write_text("not a directory\n", encoding="utf-8")
                else:
                    skills.mkdir()
                    (skills / "unknown.txt").write_text("unowned\n", encoding="utf-8")

                findings = renderer.find_projection_drift(root, "codex")
                self.assertEqual(1, len(findings))
                self.assertEqual(
                    "unsafe" if case != "nonempty" else "stale", findings[0].kind
                )
                with self.assertRaises((OSError, ValueError)):
                    renderer.write_projection(root, "codex")
                self.assertTrue(skills.exists() or skills.is_symlink())
                self.assertEqual([], list(outside.iterdir()))

    def test_native_inventory_rejects_every_unowned_extra_without_deleting_it(
        self,
    ) -> None:
        renderer = load_renderer()
        cases = (
            pathlib.Path(".gemini/agents/rogue.md"),
            pathlib.Path(".claude/hooks/rogue.sh"),
            pathlib.Path(".agents/skills/local-user/SKILL.md"),
        )
        for relative in cases:
            with (
                self.subTest(relative=relative),
                tempfile.TemporaryDirectory() as directory,
            ):
                root = pathlib.Path(directory)
                copy_stage00(root)
                renderer.write_native_projection(root)
                target = root / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                payload = b"user-authored unknown provider payload\n"
                target.write_bytes(payload)

                findings = renderer.find_native_projection_drift(root)
                self.assertIn(renderer.Finding(relative, "unowned"), findings)
                with self.assertRaises(ValueError):
                    renderer.write_native_projection(root)
                self.assertEqual(payload, target.read_bytes())

    def test_empty_owned_root_identity_race_restores_unknown_replacement(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            target = root / ".codex/skills"
            target.mkdir(parents=True)
            real_rename = renderer.os.rename
            injected = False

            def replace_before_capture(src, dst, *, src_dir_fd=None, dst_dir_fd=None):
                nonlocal injected
                if not injected and src == "skills":
                    injected = True
                    real_rename(
                        src,
                        ".skills.original-race",
                        src_dir_fd=src_dir_fd,
                        dst_dir_fd=dst_dir_fd,
                    )
                    renderer.os.mkdir(src, 0o755, dir_fd=src_dir_fd)
                    replacement_fd = renderer.os.open(
                        src,
                        renderer.os.O_RDONLY | renderer.os.O_DIRECTORY,
                        dir_fd=src_dir_fd,
                    )
                    try:
                        fd = renderer.os.open(
                            "unknown.txt",
                            renderer.os.O_WRONLY
                            | renderer.os.O_CREAT
                            | renderer.os.O_EXCL,
                            0o644,
                            dir_fd=replacement_fd,
                        )
                        try:
                            renderer.os.write(fd, b"concurrent user content\n")
                        finally:
                            renderer.os.close(fd)
                    finally:
                        renderer.os.close(replacement_fd)
                return real_rename(
                    src,
                    dst,
                    src_dir_fd=src_dir_fd,
                    dst_dir_fd=dst_dir_fd,
                )

            with mock.patch.object(
                renderer.os, "rename", side_effect=replace_before_capture
            ):
                with self.assertRaises(ValueError):
                    renderer._remove_empty_owned_root(
                        root, pathlib.Path(".codex/skills")
                    )

            self.assertEqual(
                b"concurrent user content\n",
                (target / "unknown.txt").read_bytes(),
            )
            self.assertEqual([], list((root / ".codex").glob(".skills.quarantine-*")))

    def test_native_inventory_deletes_only_marker_owned_stale_and_empty_codex_root(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_stage00(root)
            renderer.write_native_projection(root)
            stale = root / ".gemini/agents/retired.md"
            stale.write_text(
                "---\nname: retired\ndescription: retired\n---\n\n"
                f"<!-- {MARKER}; source: docs/00.agent-governance/agents/agents/retired.md -->\n",
                encoding="utf-8",
            )
            (root / ".codex/skills").mkdir()

            findings = renderer.find_native_projection_drift(root)
            self.assertIn(
                renderer.Finding(pathlib.Path(".gemini/agents/retired.md"), "stale"),
                findings,
            )
            self.assertIn(
                renderer.Finding(pathlib.Path(".codex/skills"), "stale"),
                findings,
            )
            renderer.write_native_projection(root)
            self.assertFalse(stale.exists())
            self.assertFalse((root / ".codex/skills").exists())

    def test_native_inventory_reports_unsafe_types_and_expected_mode_drift(
        self,
    ) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory) / "root"
            outside = pathlib.Path(directory) / "outside"
            root.mkdir()
            outside.write_text("sentinel\n", encoding="utf-8")
            copy_stage00(root)
            renderer.write_native_projection(root)
            rogue_link = root / ".claude/hooks/rogue-link.sh"
            rogue_link.symlink_to(outside)
            fifo = root / ".gemini/agents/rogue.fifo"
            os.mkfifo(fifo)
            hook = root / ".gemini/hooks/agent-event-hook.sh"
            hook.chmod(0o644)

            findings = renderer.find_native_projection_drift(root)
            self.assertIn(
                renderer.Finding(pathlib.Path(".claude/hooks/rogue-link.sh"), "unsafe"),
                findings,
            )
            self.assertIn(
                renderer.Finding(pathlib.Path(".gemini/agents/rogue.fifo"), "unsafe"),
                findings,
            )
            self.assertIn(
                renderer.Finding(
                    pathlib.Path(".gemini/hooks/agent-event-hook.sh"), "mode"
                ),
                findings,
            )
            self.assertEqual("sentinel\n", outside.read_text(encoding="utf-8"))

    def test_wrapper_requires_zero_or_exactly_one_supported_argument(self) -> None:
        accepted = ((), ("--check",))
        rejected = (
            ("--unknown",),
            ("--check", "--unknown"),
            ("--check", "--write"),
            ("--write", "--check"),
            ("--check", "--check"),
        )
        for args in accepted:
            with self.subTest(args=args):
                result = subprocess.run(
                    ["bash", str(WRAPPER), *args],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        for args in rejected:
            with self.subTest(args=args), tempfile.TemporaryDirectory() as directory:
                fake_bin = pathlib.Path(directory) / "bin"
                fake_bin.mkdir()
                fake_python = fake_bin / "python3"
                fake_python.write_text(
                    '#!/bin/sh\n: > "$RENDERER_SENTINEL"\nexit 0\n',
                    encoding="utf-8",
                )
                fake_python.chmod(0o755)
                sentinel = pathlib.Path(directory) / "renderer-invoked"
                environment = os.environ.copy()
                environment["PATH"] = f"{fake_bin}:/usr/bin:/bin"
                environment["RENDERER_SENTINEL"] = str(sentinel)
                result = subprocess.run(
                    ["bash", str(WRAPPER), *args],
                    cwd=ROOT,
                    env=environment,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(2, result.returncode, result.stdout + result.stderr)
                self.assertIn("Usage:", result.stderr)
                self.assertFalse(sentinel.exists())


if __name__ == "__main__":
    unittest.main()
