from __future__ import annotations

import importlib.util
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

import yaml


ROOT = pathlib.Path(__file__).resolve().parents[2]
RENDERER = ROOT / "scripts/operations/provider_surface_renderer.py"
WRAPPER = ROOT / "scripts/operations/sync-provider-surfaces.sh"


def _child_env() -> dict[str, str]:
    """Return an environment for a non-gate subprocess owned by this test."""

    environment = dict(os.environ)
    environment.pop("HYHOME_CI_GATE_ROOT", None)
    return environment


def load_renderer():
    spec = importlib.util.spec_from_file_location("provider_surface_renderer", RENDERER)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {RENDERER}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def copy_fixture(root: pathlib.Path) -> None:
    shutil.copytree(ROOT / "docs/00.agent-governance", root / "docs/00.agent-governance")
    registry = root / "docs/99.templates/registry.json"
    registry.parent.mkdir(parents=True)
    shutil.copy2(ROOT / "docs/99.templates/registry.json", registry)
    for directory in (".agents", ".claude", ".codex"):
        shutil.copytree(ROOT / directory, root / directory)
    hook = root / "scripts/hooks/agent-event-hook.sh"
    hook.parent.mkdir(parents=True)
    shutil.copy2(ROOT / "scripts/hooks/agent-event-hook.sh", hook)


def mutate_registry(root: pathlib.Path, mutation) -> None:
    path = root / "docs/00.agent-governance/providers/registry.yaml"
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    mutation(data)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


class ProviderSurfaceRendererTests(unittest.TestCase):
    def test_repository_projection_is_exact(self) -> None:
        renderer = load_renderer()
        self.assertEqual([], renderer.find_native_projection_drift(ROOT))

    def test_write_repairs_registered_projection_drift(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            target = root / ".agents/agents/code-reviewer.md"
            target.write_text("drift\n")
            self.assertTrue(renderer.find_native_projection_drift(root))
            renderer.write_native_projection(root)
            self.assertEqual([], renderer.find_native_projection_drift(root))

    def test_write_isolates_stale_generated_projection_and_fails_closed(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            stale = root / ".agents/skills/stale/SKILL.md"
            stale.parent.mkdir(parents=True)
            stale.write_text(
                "---\nname: stale\n---\n\n"
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; "
                "source: docs/00.agent-governance/skills/stale.md -->\n"
            )
            with self.assertRaisesRegex(ValueError, "retained.*quarantine"):
                renderer.write_native_projection(root)
            self.assertFalse(stale.exists())
            quarantined = tuple((root / renderer.QUARANTINE_ROOT).iterdir())
            self.assertEqual(1, len(quarantined))
            self.assertTrue(renderer._is_generated(quarantined[0].read_bytes()))

    def test_write_preserves_unowned_projection_file(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            unowned = root / ".agents/skills/local/SKILL.md"
            unowned.parent.mkdir(parents=True)
            unowned.write_text("# local\n")
            with self.assertRaisesRegex(ValueError, "unowned"):
                renderer.write_native_projection(root)
            self.assertTrue(unowned.exists())

    def test_managed_roots_reject_escape_and_unregistered_values(self) -> None:
        renderer = load_renderer()
        mutations = {
            "absolute": lambda data: data.update({"generated_roots": ["/tmp"]}),
            "parent": lambda data: data.update({"generated_roots": ["../outside"]}),
            "unexpected": lambda data: data["generated_roots"].append(".agents/other"),
            "missing": lambda data: data.update(
                {"generated_roots": data["generated_roots"][:-1]}
            ),
        }
        for name, mutation in mutations.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as directory:
                root = pathlib.Path(directory)
                copy_fixture(root)
                mutate_registry(root, mutation)
                with self.assertRaises((ValueError, renderer.ContractLoadError)):
                    renderer.write_native_projection(root)

    def test_managed_root_symlink_is_rejected(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            managed = root / ".agents/agents"
            outside = root / "outside"
            shutil.rmtree(managed)
            outside.mkdir()
            managed.symlink_to(outside, target_is_directory=True)
            with self.assertRaisesRegex(ValueError, "symlink"):
                renderer.write_native_projection(root)

    def test_marker_inside_unowned_file_is_not_ownership_proof(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            unowned = root / ".agents/skills/local/SKILL.md"
            unowned.parent.mkdir(parents=True)
            unowned.write_text(
                "# local file\n\n"
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; "
                "source: docs/00.agent-governance/skills/local.md -->\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ValueError, "unowned"):
                renderer.write_native_projection(root)
            self.assertTrue(unowned.exists())

    def test_replacement_race_preserves_new_unowned_file(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            relative = pathlib.PurePosixPath(".agents/skills/stale/SKILL.md")
            stale = root / relative
            stale.parent.mkdir(parents=True)
            stale.write_text(
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; "
                "source: docs/00.agent-governance/skills/stale.md -->\n",
                encoding="utf-8",
            )
            identity = renderer._owned_projection_identity(root, relative)
            stale.unlink()
            stale.write_text("# replacement owned by user\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "changed"):
                renderer._unlink_owned_projection(root, relative, identity)
            self.assertEqual("# replacement owned by user\n", stale.read_text())

    def test_validation_to_unlink_replacement_race_preserves_user_file(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            relative = pathlib.PurePosixPath(".agents/skills/stale/SKILL.md")
            stale = root / relative
            stale.parent.mkdir(parents=True)
            stale.write_text(
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; "
                "source: docs/00.agent-governance/skills/stale.md -->\n",
                encoding="utf-8",
            )
            identity = renderer._owned_projection_identity(root, relative)
            real_stat = os.stat
            replaced = False

            def replace_after_stat(path, *args, **kwargs):
                nonlocal replaced
                metadata = real_stat(path, *args, **kwargs)
                if (
                    not replaced
                    and path == relative.name
                    and kwargs.get("dir_fd") is not None
                    and kwargs.get("follow_symlinks") is False
                ):
                    replaced = True
                    os.unlink(stale)
                    descriptor = os.open(stale, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
                    try:
                        os.write(descriptor, b"# replacement owned by user\n")
                    finally:
                        os.close(descriptor)
                return metadata

            with mock.patch.object(renderer.os, "stat", side_effect=replace_after_stat):
                with self.assertRaisesRegex(ValueError, "changed"):
                    renderer._unlink_owned_projection(root, relative, identity)
            self.assertTrue(replaced)
            self.assertEqual("# replacement owned by user\n", stale.read_text())

    def test_post_validation_quarantine_replacement_is_retained(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            relative = pathlib.PurePosixPath(".agents/skills/stale/SKILL.md")
            stale = root / relative
            stale.parent.mkdir(parents=True)
            stale.write_text(
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; "
                "source: docs/00.agent-governance/skills/stale.md -->\n",
                encoding="utf-8",
            )
            identity = renderer._owned_projection_identity(root, relative)
            replacement = b"# post-validation user replacement\n"
            real_identity_at = renderer._owned_projection_identity_at
            replaced = False

            def replace_after_quarantine_validation(descriptor, candidate):
                nonlocal replaced
                actual = real_identity_at(descriptor, candidate)
                if not replaced and ".delete-" in candidate.name:
                    replaced = True
                    os.unlink(candidate.name, dir_fd=descriptor)
                    handle = os.open(
                        candidate.name,
                        os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                        0o600,
                        dir_fd=descriptor,
                    )
                    try:
                        os.write(handle, replacement)
                    finally:
                        os.close(handle)
                return actual

            with mock.patch.object(
                renderer,
                "_owned_projection_identity_at",
                side_effect=replace_after_quarantine_validation,
            ):
                with self.assertRaisesRegex(ValueError, "retained.*quarantine|changed"):
                    renderer._unlink_owned_projection(root, relative, identity)
            self.assertTrue(replaced)
            survivors = [
                path
                for path in root.rglob("*")
                if path.is_file() and path.read_bytes() == replacement
            ]
            self.assertTrue(survivors)

    def test_post_write_managed_root_symlink_race_preserves_outside_directory(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            managed = root / ".agents/skills"
            displaced = root / "displaced-skills"
            outside = root / "outside"
            outside_child = outside / "must-survive"
            outside_child.mkdir(parents=True)
            expected_write_count = len(renderer.expected_native_projection(root))
            real_atomic_write = renderer._atomic_write
            writes = 0

            def replace_after_last_write(source_root, relative, content):
                nonlocal writes
                real_atomic_write(source_root, relative, content)
                writes += 1
                if writes == expected_write_count:
                    managed.rename(displaced)
                    managed.symlink_to(outside, target_is_directory=True)

            with mock.patch.object(
                renderer, "_atomic_write", side_effect=replace_after_last_write
            ):
                with self.assertRaisesRegex(ValueError, "managed root.*symlink|changed"):
                    renderer.write_native_projection(root)
            self.assertEqual(expected_write_count, writes)
            self.assertTrue(outside_child.is_dir())

    def test_parent_replacement_race_preserves_outside_projection(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_fixture(root)
            relative = pathlib.PurePosixPath(".agents/skills/stale/SKILL.md")
            stale = root / relative
            stale.parent.mkdir(parents=True)
            stale.write_text(
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; "
                "source: docs/00.agent-governance/skills/stale.md -->\n",
                encoding="utf-8",
            )
            identity = renderer._owned_projection_identity(root, relative)
            outside = root / "outside"
            outside.mkdir()
            outside_file = outside / "SKILL.md"
            outside_file.write_text("# outside user file\n", encoding="utf-8")
            shutil.rmtree(stale.parent)
            stale.parent.symlink_to(outside, target_is_directory=True)
            with self.assertRaisesRegex(ValueError, "changed"):
                renderer._unlink_owned_projection(root, relative, identity)
            self.assertEqual("# outside user file\n", outside_file.read_text())

    def test_wrapper_check_is_clean(self) -> None:
        result = subprocess.run(
            ["bash", str(WRAPPER), "--check"],
            cwd=ROOT,
            env=_child_env(),
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("providers=2", result.stdout)


if __name__ == "__main__":
    unittest.main()
