from __future__ import annotations

import importlib.util
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


ROOT = pathlib.Path(__file__).resolve().parents[2]
RENDERER = ROOT / "scripts/operations/provider_surface_renderer.py"


def load_renderer():
    spec = importlib.util.spec_from_file_location("provider_surface_renderer", RENDERER)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load renderer: {RENDERER}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def copy_stage00(root: pathlib.Path) -> None:
    shutil.copytree(
        ROOT / "docs/00.agent-governance",
        root / "docs/00.agent-governance",
        dirs_exist_ok=True,
    )


class ProviderSurfaceRendererTests(unittest.TestCase):
    def test_catalog_load_and_render_are_deterministic_stage00_only(self) -> None:
        renderer = load_renderer()
        catalog = renderer.load_catalog(ROOT)
        self.assertEqual(14, len(catalog.agents))
        self.assertEqual(22, len(catalog.functions))
        self.assertEqual(
            sorted(record.agent_id for record in catalog.agents),
            [record.agent_id for record in catalog.agents],
        )
        self.assertEqual(
            sorted(record.function_id for record in catalog.functions),
            [record.function_id for record in catalog.functions],
        )

        function = next(
            record for record in catalog.functions if record.function_id == "code-reviewer"
        )
        first = renderer.render_function("claude", function)
        second = renderer.render_function("claude", function)
        self.assertEqual(first, second)
        self.assertIn(b"Generated by scripts/operations/provider_surface_renderer.py", first)
        self.assertIn(
            b"docs/00.agent-governance/agents/functions/code-reviewer.md", first
        )

        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_stage00(root)
            before = renderer.expected_projection(root, "claude")
            local_override = root / ".claude/skills/code-reviewer/SKILL.md"
            local_override.parent.mkdir(parents=True, exist_ok=True)
            local_override.write_text("provider-local policy must not be input\n", encoding="utf-8")
            after = renderer.expected_projection(root, "claude")
            self.assertEqual(before, after)

    def test_check_is_read_only_and_write_is_idempotent_with_bounded_stale_cleanup(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            copy_stage00(root)

            legacy = root / ".claude/skills/code-reviewer/skill.md"
            legacy.parent.mkdir(parents=True, exist_ok=True)
            legacy.write_text("legacy lowercase entrypoint\n", encoding="utf-8")
            codex_legacy = root / ".codex/skills/code-reviewer/skill.md"
            codex_legacy.parent.mkdir(parents=True, exist_ok=True)
            codex_legacy.write_text("obsolete codex skill\n", encoding="utf-8")
            managed_stale = root / ".agents/skills/retired/SKILL.md"
            managed_stale.parent.mkdir(parents=True, exist_ok=True)
            managed_stale.write_text(
                "<!-- Generated by scripts/operations/provider_surface_renderer.py; source: retired -->\n",
                encoding="utf-8",
            )
            unowned = root / ".agents/skills/local-user/SKILL.md"
            unowned.parent.mkdir(parents=True, exist_ok=True)
            unowned.write_text("unowned local surface\n", encoding="utf-8")
            unowned_lowercase = root / ".claude/skills/local-user/skill.md"
            unowned_lowercase.parent.mkdir(parents=True, exist_ok=True)
            unowned_lowercase.write_text("unowned lowercase surface\n", encoding="utf-8")

            check = subprocess.run(
                [sys.executable, str(RENDERER), "--root", str(root), "--check"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(1, check.returncode)
            self.assertIn("projection drift", check.stderr)
            self.assertTrue(legacy.is_file())
            self.assertFalse((root / ".claude/skills/code-reviewer/SKILL.md").exists())

            write = subprocess.run(
                [sys.executable, str(RENDERER), "--root", str(root), "--write"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(0, write.returncode, write.stdout + write.stderr)
            self.assertFalse(legacy.exists())
            self.assertFalse(codex_legacy.exists())
            self.assertFalse(managed_stale.exists())
            self.assertTrue(unowned.is_file())
            self.assertTrue(unowned_lowercase.is_file())
            self.assertEqual(22, len(list((root / ".claude/skills").glob("*/SKILL.md"))))
            self.assertEqual(23, len(list((root / ".agents/skills").glob("*/SKILL.md"))))

            snapshot = {
                path.relative_to(root).as_posix(): path.read_bytes()
                for path in root.rglob("*")
                if path.is_file()
            }
            second_write = subprocess.run(
                [sys.executable, str(RENDERER), "--root", str(root), "--write"],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(0, second_write.returncode)
            self.assertEqual(
                snapshot,
                {
                    path.relative_to(root).as_posix(): path.read_bytes()
                    for path in root.rglob("*")
                    if path.is_file()
                },
            )

            for _ in range(2):
                clean = subprocess.run(
                    [sys.executable, str(RENDERER), "--root", str(root), "--check"],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(0, clean.returncode, clean.stdout + clean.stderr)
                self.assertIn("provider_surface_renderer: PASS", clean.stdout)

    def test_write_rejects_symlinked_managed_parent_without_external_writes(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory) / "root"
            outside = pathlib.Path(directory) / "outside"
            root.mkdir()
            outside.mkdir()
            copy_stage00(root)
            (root / ".claude").mkdir()
            (root / ".claude/skills").symlink_to(outside, target_is_directory=True)

            with self.assertRaises((OSError, ValueError)):
                renderer.write_projection(root, "claude")
            self.assertEqual([], list(outside.iterdir()))

    def test_check_reports_symlinked_output_as_unsafe_without_following_it(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory) / "root"
            outside = pathlib.Path(directory) / "outside-sentinel"
            root.mkdir()
            copy_stage00(root)
            renderer.write_projection(root, "claude")
            target = root / ".claude/skills/code-reviewer/SKILL.md"
            target.unlink()
            outside.write_text("outside provider-local payload\n", encoding="utf-8")
            target.symlink_to(outside)

            findings = renderer.find_projection_drift(root, "claude")
            matching = [finding for finding in findings if finding.path == target.relative_to(root)]
            self.assertEqual(["unsafe"], [finding.kind for finding in matching])

            stale = root / ".agents/skills/retired/SKILL.md"
            stale.parent.mkdir(parents=True, exist_ok=True)
            stale.symlink_to(outside)
            with self.assertRaises(ValueError):
                renderer.find_managed_stale_files(root, {})

    def test_confined_write_cleans_temporary_file_after_write_failure(self) -> None:
        renderer = load_renderer()
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            target = pathlib.Path(".claude/skills/code-reviewer/SKILL.md")
            with mock.patch.object(renderer.os, "write", side_effect=OSError("injected")):
                with self.assertRaises(OSError):
                    renderer._write_confined(root, target, b"content")
            self.assertFalse((root / target).exists())
            self.assertEqual(
                [], list((root / target.parent).glob(f".{target.name}.tmp-*"))
            )

    def test_unknown_flags_fail_closed(self) -> None:
        result = subprocess.run(
            [sys.executable, str(RENDERER), "--check", "--unknown"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(2, result.returncode)
        self.assertIn("unrecognized arguments", result.stderr)


if __name__ == "__main__":
    unittest.main()
