"""Focused static metadata/profile API shared by document validators."""

from __future__ import annotations

from scripts.lib.document_governance.metadata_validator import (
    EXPECTED_EXCEPTION_SCHEMA,
    TARGET_MARKDOWN_PREFIXES,
    Finding,
    FrontmatterError,
    ProfileError,
    Record,
    _parse_frontmatter_text,
    _record_from_text,
    _safe_load_unique,
    _safe_repo_path,
    _valid_metadata_artifact_id,
    build_manifest,
    build_registry_profiles,
    build_registry_transition_profiles,
    collect_records_at_ref,
    infer_artifact_type,
    load_profiles,
    matching_template_roles,
    registered_generated_owner,
    validate_body_contract,
    validate_record,
    validate_static_exception_document,
    validate_static_migration_manifest,
)
from scripts.lib.document_governance.registry import (
    DEFAULT_REGISTRY,
    DocumentRegistry,
    IdentitySpace,
    RegistryError,
    RegistryFinding,
    load_registry,
    validate_frontmatter,
    validate_registry,
)

__all__ = (
    "EXPECTED_EXCEPTION_SCHEMA",
    "TARGET_MARKDOWN_PREFIXES",
    "Finding",
    "FrontmatterError",
    "ProfileError",
    "Record",
    "_parse_frontmatter_text",
    "_record_from_text",
    "_safe_load_unique",
    "_safe_repo_path",
    "_valid_metadata_artifact_id",
    "build_manifest",
    "build_registry_profiles",
    "build_registry_transition_profiles",
    "collect_records_at_ref",
    "infer_artifact_type",
    "load_profiles",
    "matching_template_roles",
    "registered_generated_owner",
    "validate_body_contract",
    "validate_record",
    "validate_static_exception_document",
    "validate_static_migration_manifest",
    "DEFAULT_REGISTRY",
    "DocumentRegistry",
    "IdentitySpace",
    "RegistryError",
    "RegistryFinding",
    "load_registry",
    "validate_frontmatter",
    "validate_registry",
)
