x-tier-label: &tier-label
  hy-home.tier: admin


volumes:
  dozzle-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_MANAGEMENT_DIR}/dozzle

services:
  dozzle:
    profiles:
      - admin
    extends:
      file: ../../common-optimizations.yml
      service: template-stateful-med
    container_name: dozzle
    image: amir20/dozzle:v10.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle-data:/data
    expose:
      - ${DOZZLE_PORT:-8080}
    healthcheck:
      test: ['CMD', '/dozzle', 'healthcheck']
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      <<: *tier-label
      traefik.enable: 'true'
      traefik.http.routers.dozzle.rule: Host(`dozzle.${DEFAULT_URL}`)
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.tls: 'true'
      traefik.http.middlewares.dozzle-admin-ip.ipallowlist.sourcerange: ${LAB_ALLOWED_CIDRS:-127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      traefik.http.routers.dozzle.middlewares: gateway-standard-chain@file,dozzle-admin-ip@docker,sso-errors@file,sso-auth@file
      traefik.http.services.dozzle.loadbalancer.server.port: ${DOZZLE_PORT:-8080}
    networks:
      infra_net:
        ipv4_address: 172.19.0.6
