#!/usr/bin/env python3
"""Render deterministic shared skill projections from canonical Stage 00 sources."""

from __future__ import annotations

import argparse
import contextlib
import os
import pathlib
import posixpath
import re
import secrets
import stat
import sys
import urllib.parse
from collections.abc import Mapping
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parents[2]
VALIDATION_DIR = ROOT / "scripts/validation"
if str(VALIDATION_DIR) not in sys.path:
    sys.path.insert(0, str(VALIDATION_DIR))

from agent_governance_contract import (  # noqa: E402
    ContractLoadError,
    load_contract_bundle,
    read_repository_text,
    validate_contract_bundle,
)


GENERATED_MARKER = "Generated by scripts/operations/provider_surface_renderer.py"
GENERATED_SURFACE_PREFIX_PATTERN = re.compile(
    rb"\A---\n"
    rb"name: (?P<function_id>[a-z0-9]+(?:-[a-z0-9]+)*)\n"
    rb"description: Canonical [a-z0-9-]+ function for (?P=function_id); "
    rb"owned by [a-z0-9]+(?:-[a-z0-9]+)*\.\n"
    rb"---\n\n"
    rb"<!-- Generated by scripts/operations/provider_surface_renderer\.py; "
    rb"source: docs/00\.agent-governance/agents/functions/"
    rb"(?P=function_id)\.md -->\n\n"
)
INLINE_LINK_PATTERN = re.compile(
    r"(?P<prefix>!?\[[^\]\n]*\]\()"
    r"(?P<destination><[^>\n]+>|[^\s)]+)"
    r"(?P<title>\s+(?:\"[^\"\n]*\"|'[^'\n]*'|\([^()\n]*\)))?"
    r"(?P<suffix>\))"
)
REFERENCE_LINK_PATTERN = re.compile(
    r"(?m)^(?P<prefix>[ \t]{0,3}\[[^\]\n]+\]:[ \t]*)"
    r"(?P<destination><[^>\n]+>|\S+)"
)
SKILL_PROVIDERS = ("agents-md", "claude")
MIGRATION_PROVIDERS = (*SKILL_PROVIDERS, "codex")
LEGACY_SKILL_IDS = frozenset(
    {
        "adr-writing",
        "ci-cd-patterns",
        "code-review-dimensions",
        "code-reviewer",
        "compose-stack-agent",
        "container-threat-modeling",
        "deployment-pipeline-design",
        "docker-compose-patterns",
        "e2e-testing",
        "execution-plan-agent",
        "incident-response",
        "infra-cross-validate",
        "infra-validate",
        "knowledge-map-agent",
        "ops-runbook-agent",
        "policy-gate-agent",
        "requirements-to-design-agent",
        "security-audit",
        "style-validation",
        "task-breakdown-agent",
        "test-automator",
        "workspace-audit-revalidation",
    }
)


@dataclass(frozen=True)
class AgentRecord:
    agent_id: str
    scope: str
    tier: str
    category: str
    catalog_path: str
    source_text: str


@dataclass(frozen=True)
class FunctionRecord:
    function_id: str
    scope: str
    catalog_path: str
    owner_agent: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    gates: tuple[str, ...]
    source_text: str


@dataclass(frozen=True)
class Catalog:
    agents: tuple[AgentRecord, ...]
    functions: tuple[FunctionRecord, ...]


@dataclass(frozen=True, order=True)
class Finding:
    path: pathlib.Path
    kind: str


def _frontmatter_free_body(text: str) -> str:
    if not text.startswith("---\n"):
        return text.strip() + "\n"
    boundary = text.find("\n---\n", 4)
    if boundary < 0:
        raise ValueError("canonical source has unterminated frontmatter")
    return text[boundary + 5 :].strip() + "\n"


def _rebase_link_destination(
    destination: str,
    source_path: pathlib.PurePosixPath,
    output_path: pathlib.PurePosixPath,
) -> str:
    bracketed = destination.startswith("<") and destination.endswith(">")
    raw = destination[1:-1] if bracketed else destination
    parsed = urllib.parse.urlsplit(raw)
    if (
        not parsed.path
        or raw.startswith(("#", "/", "//"))
        or parsed.scheme
        or parsed.netloc
    ):
        return destination
    canonical_target = posixpath.normpath(
        posixpath.join(source_path.parent.as_posix(), parsed.path)
    )
    if canonical_target == ".." or canonical_target.startswith("../"):
        raise ValueError("canonical Markdown link escapes the repository")
    rebased_path = posixpath.relpath(
        canonical_target, output_path.parent.as_posix()
    )
    rebased = urllib.parse.urlunsplit(
        ("", "", rebased_path, parsed.query, parsed.fragment)
    )
    return f"<{rebased}>" if bracketed else rebased


def _rebase_markdown_links(
    body: str,
    source_path: pathlib.PurePosixPath,
    output_path: pathlib.PurePosixPath,
) -> str:
    def replace_inline(match: re.Match[str]) -> str:
        destination = _rebase_link_destination(
            match.group("destination"), source_path, output_path
        )
        return (
            f'{match.group("prefix")}{destination}'
            f'{match.group("title") or ""}{match.group("suffix")}'
        )

    def replace_reference(match: re.Match[str]) -> str:
        destination = _rebase_link_destination(
            match.group("destination"), source_path, output_path
        )
        return f'{match.group("prefix")}{destination}'

    return REFERENCE_LINK_PATTERN.sub(
        replace_reference, INLINE_LINK_PATTERN.sub(replace_inline, body)
    )


def _has_exact_generated_marker(content: bytes) -> bool:
    return GENERATED_SURFACE_PREFIX_PATTERN.match(content) is not None


def load_catalog(root: pathlib.Path) -> Catalog:
    root = root.absolute()
    bundle = load_contract_bundle(root)
    findings = validate_contract_bundle(root, bundle)
    if findings:
        raise ValueError("canonical Stage 00 contract is invalid")

    agents = tuple(
        AgentRecord(
            agent_id=str(entry["agent_id"]),
            scope=str(entry["scope"]),
            tier=str(entry["tier"]),
            category=str(entry["category"]),
            catalog_path=str(entry["catalog_path"]),
            source_text=read_repository_text(root, str(entry["catalog_path"])),
        )
        for entry in sorted(bundle.catalog["agents"], key=lambda item: item["agent_id"])
    )
    functions = tuple(
        FunctionRecord(
            function_id=str(entry["function_id"]),
            scope=str(entry["scope"]),
            catalog_path=str(entry["catalog_path"]),
            owner_agent=str(entry["owner_agent"]),
            inputs=tuple(str(item) for item in entry["inputs"]),
            outputs=tuple(str(item) for item in entry["outputs"]),
            gates=tuple(str(item) for item in entry["gates"]),
            source_text=read_repository_text(root, str(entry["catalog_path"])),
        )
        for entry in sorted(
            bundle.catalog["functions"], key=lambda item: item["function_id"]
        )
    )
    return Catalog(agents=agents, functions=functions)


def render_agent(provider: str, agent: AgentRecord) -> bytes:
    if provider not in {"agents-md", "claude", "codex", "gemini"}:
        raise ValueError(f"unsupported provider: {provider}")
    source = agent.catalog_path
    if provider == "codex":
        return (
            f'name = "{agent.agent_id}"\n'
            f'layer = "{agent.scope}"\n'
            f'source_catalog = "{source}"\n'
        ).encode()
    return (
        "---\n"
        f"name: {agent.agent_id}\n"
        f"description: Canonical {agent.scope} role projection for {agent.agent_id}.\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER}; source: {source} -->\n\n"
        f"@{source}\n"
    ).encode()


def render_function(provider: str, function: FunctionRecord) -> bytes:
    if provider not in {"agents-md", "claude", "gemini"}:
        raise ValueError(f"unsupported provider: {provider}")
    output_root = {
        "agents-md": pathlib.PurePosixPath(".agents/skills"),
        "claude": pathlib.PurePosixPath(".claude/skills"),
        "gemini": pathlib.PurePosixPath(".gemini/skills"),
    }[provider]
    output_path = output_root / function.function_id / "SKILL.md"
    source_path = pathlib.PurePosixPath(function.catalog_path)
    body = _rebase_markdown_links(
        _frontmatter_free_body(function.source_text), source_path, output_path
    )
    description = (
        f"Canonical {function.scope} function for {function.function_id}; "
        f"owned by {function.owner_agent}."
    )
    return (
        "---\n"
        f"name: {function.function_id}\n"
        f"description: {description}\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER}; source: {function.catalog_path} -->\n\n"
        f"{body}"
    ).encode()


def expected_projection(
    root: pathlib.Path, provider: str
) -> Mapping[pathlib.Path, bytes]:
    if provider not in MIGRATION_PROVIDERS:
        raise ValueError(f"unsupported projection: {provider}")
    if provider == "codex":
        return {}
    catalog = load_catalog(root)
    base = pathlib.Path(".claude/skills" if provider == "claude" else ".agents/skills")
    return {
        base / function.function_id / "SKILL.md": render_function(
            provider, function
        )
        for function in catalog.functions
    }


def _owned_root(provider: str) -> pathlib.Path:
    if provider == "claude":
        return pathlib.Path(".claude/skills")
    if provider == "agents-md":
        return pathlib.Path(".agents/skills")
    if provider == "codex":
        return pathlib.Path(".codex/skills")
    raise ValueError(f"unsupported projection: {provider}")


def find_managed_stale_files(
    root: pathlib.Path, expected: Mapping[pathlib.Path, bytes]
) -> set[pathlib.Path]:
    expected_paths = set(expected)
    stale: set[pathlib.Path] = set()
    for provider in MIGRATION_PROVIDERS:
        owned = root / _owned_root(provider)
        if not owned.exists() and not owned.is_symlink():
            continue
        _assert_confined_directory(root, _owned_root(provider))
        for function_id in sorted(LEGACY_SKILL_IDS):
            path = owned / function_id / "skill.md"
            if path.exists() or path.is_symlink():
                stale.add(path.relative_to(root))
        for path in owned.glob("*/SKILL.md"):
            relative = path.relative_to(root)
            if relative in expected_paths:
                continue
            try:
                content = read_repository_text(root, relative.as_posix())
            except ContractLoadError as error:
                raise ValueError("managed projection entry is unsafe") from error
            if _has_exact_generated_marker(content.encode()):
                stale.add(relative)
    return stale


def _assert_confined_directory(root: pathlib.Path, relative: pathlib.Path) -> None:
    current = root
    for part in relative.parts:
        current = current / part
        if not current.exists() and not current.is_symlink():
            return
        mode = current.lstat().st_mode
        if stat.S_ISLNK(mode) or not stat.S_ISDIR(mode):
            raise ValueError("managed projection directory is unsafe")


def find_projection_drift(
    root: pathlib.Path, provider: str
) -> list[Finding]:
    if provider == "codex":
        owned_root = _owned_root(provider)
        absolute = root / owned_root
        if not absolute.exists() and not absolute.is_symlink():
            return []
        try:
            _assert_confined_directory(root, owned_root)
        except (OSError, ValueError):
            return [Finding(owned_root, "unsafe")]
        return [Finding(owned_root, "stale")]
    expected = expected_projection(root, provider)
    findings: list[Finding] = []
    for path, content in expected.items():
        try:
            current = read_repository_text(root, path.as_posix()).encode()
        except ContractLoadError as error:
            kind = "missing" if error.code == "AGC-REPOSITORY-FILE-MISSING" else "unsafe"
            findings.append(Finding(path, kind))
            continue
        if current != content:
            findings.append(Finding(path, "content"))
    owned_expected = {
        path: content for path, content in expected.items() if path.is_relative_to(_owned_root(provider))
    }
    for path in sorted(find_managed_stale_files(root, owned_expected)):
        if path.is_relative_to(_owned_root(provider)):
            findings.append(Finding(path, "stale"))
    return sorted(set(findings))


@contextlib.contextmanager
def _open_confined_directory(
    root: pathlib.Path, relative: pathlib.Path, *, create: bool
):
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    directory_flags |= getattr(os, "O_CLOEXEC", 0)
    descriptors: list[int] = []
    try:
        current = os.open(root, directory_flags)
        descriptors.append(current)
        for part in relative.parts:
            try:
                child = os.open(part, directory_flags, dir_fd=current)
            except FileNotFoundError:
                if not create:
                    raise
                os.mkdir(part, 0o755, dir_fd=current)
                child = os.open(part, directory_flags, dir_fd=current)
            descriptors.append(child)
            current = child
        yield current
    finally:
        for descriptor in reversed(descriptors):
            try:
                os.close(descriptor)
            except OSError:
                pass


def _read_regular_fd(parent_fd: int, name: str) -> bytes | None:
    flags = os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW
    flags |= getattr(os, "O_CLOEXEC", 0)
    try:
        descriptor = os.open(name, flags, dir_fd=parent_fd)
    except FileNotFoundError:
        return None
    try:
        if not stat.S_ISREG(os.fstat(descriptor).st_mode):
            raise ValueError("managed projection output is not a regular file")
        chunks: list[bytes] = []
        while True:
            chunk = os.read(descriptor, 64 * 1024)
            if not chunk:
                return b"".join(chunks)
            chunks.append(chunk)
    finally:
        os.close(descriptor)


def _write_confined(root: pathlib.Path, relative: pathlib.Path, content: bytes) -> None:
    with _open_confined_directory(root, relative.parent, create=True) as parent_fd:
        current = _read_regular_fd(parent_fd, relative.name)
        if current == content:
            return
        temporary = f".{relative.name}.tmp-{secrets.token_hex(12)}"
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
        flags |= getattr(os, "O_CLOEXEC", 0)
        descriptor = os.open(temporary, flags, 0o644, dir_fd=parent_fd)
        try:
            try:
                view = memoryview(content)
                while view:
                    written = os.write(descriptor, view)
                    if written <= 0:
                        raise OSError("managed projection write made no progress")
                    view = view[written:]
                os.fsync(descriptor)
            finally:
                os.close(descriptor)
                descriptor = -1
            os.replace(
                temporary,
                relative.name,
                src_dir_fd=parent_fd,
                dst_dir_fd=parent_fd,
            )
        except BaseException:
            if descriptor >= 0:
                try:
                    os.close(descriptor)
                except OSError:
                    pass
            try:
                os.unlink(temporary, dir_fd=parent_fd)
            except OSError:
                pass
            raise


def _restore_quarantine(parent_fd: int, quarantine: str, original: str) -> None:
    try:
        os.link(
            quarantine,
            original,
            src_dir_fd=parent_fd,
            dst_dir_fd=parent_fd,
            follow_symlinks=False,
        )
    except OSError as error:
        raise ValueError(
            "managed stale output could not be restored without overwrite"
        ) from error
    try:
        os.unlink(quarantine, dir_fd=parent_fd)
    except OSError as error:
        raise ValueError("managed stale output quarantine cleanup failed") from error


def _new_quarantine_name(parent_fd: int, name: str) -> str:
    for _ in range(8):
        candidate = f".{name}.quarantine-{secrets.token_hex(12)}"
        try:
            os.stat(candidate, dir_fd=parent_fd, follow_symlinks=False)
        except FileNotFoundError:
            return candidate
    raise ValueError("managed stale output quarantine allocation failed")


def _remove_stale_confined(
    root: pathlib.Path, relative: pathlib.Path, *, require_marker: bool
) -> None:
    with _open_confined_directory(root, relative.parent, create=False) as parent_fd:
        quarantine = _new_quarantine_name(parent_fd, relative.name)
        try:
            os.rename(
                relative.name,
                quarantine,
                src_dir_fd=parent_fd,
                dst_dir_fd=parent_fd,
            )
        except FileNotFoundError:
            return
        try:
            captured = _read_regular_fd(parent_fd, quarantine)
            if captured is None:
                raise ValueError("managed stale output capture disappeared")
            if require_marker and not _has_exact_generated_marker(captured):
                raise ValueError("managed stale output ownership changed")
        except (OSError, ValueError) as error:
            _restore_quarantine(parent_fd, quarantine, relative.name)
            raise ValueError("managed stale output is unsafe or unowned") from error
        os.unlink(quarantine, dir_fd=parent_fd)


def _remove_empty_owned_root(root: pathlib.Path, relative: pathlib.Path) -> None:
    try:
        with _open_confined_directory(root, relative.parent, create=False) as parent_fd:
            directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
            directory_flags |= getattr(os, "O_CLOEXEC", 0)
            try:
                owned_fd = os.open(relative.name, directory_flags, dir_fd=parent_fd)
            except FileNotFoundError:
                return
            try:
                if os.listdir(owned_fd):
                    raise ValueError("obsolete owned root contains unknown entries")
                identity = os.fstat(owned_fd)
                quarantine = _new_quarantine_name(parent_fd, relative.name)
                os.rename(
                    relative.name,
                    quarantine,
                    src_dir_fd=parent_fd,
                    dst_dir_fd=parent_fd,
                )
                captured = os.stat(
                    quarantine, dir_fd=parent_fd, follow_symlinks=False
                )
                if (captured.st_dev, captured.st_ino) != (
                    identity.st_dev,
                    identity.st_ino,
                ):
                    raise ValueError("obsolete owned root identity changed")
                if os.listdir(owned_fd):
                    raise ValueError("obsolete owned root changed during removal")
                os.rmdir(quarantine, dir_fd=parent_fd)
            finally:
                os.close(owned_fd)
    except FileNotFoundError:
        return


def write_projection(root: pathlib.Path, provider: str) -> None:
    expected = expected_projection(root, provider)
    owned_root = _owned_root(provider)
    _assert_confined_directory(root, owned_root)
    for relative in sorted(find_managed_stale_files(root, expected)):
        if not relative.is_relative_to(owned_root):
            continue
        is_legacy = relative.name == "skill.md"
        _remove_stale_confined(root, relative, require_marker=not is_legacy)
        if provider == "codex" and is_legacy:
            _remove_empty_owned_root(root, relative.parent)
    if provider == "codex":
        _remove_empty_owned_root(root, owned_root)
    for relative, content in sorted(expected.items()):
        _write_confined(root, relative, content)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render Stage 00 canonical shared skill projections."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=pathlib.Path, default=ROOT)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.root.absolute()
    try:
        if args.write:
            for provider in MIGRATION_PROVIDERS:
                write_projection(root, provider)
        findings = [
            (provider, finding)
            for provider in MIGRATION_PROVIDERS
            for finding in find_projection_drift(root, provider)
        ]
    except (ContractLoadError, OSError, ValueError) as error:
        print(f"provider_surface_renderer: ERROR {type(error).__name__}", file=sys.stderr)
        return 1
    if findings:
        for provider, finding in findings:
            print(
                f"projection drift: provider={provider} path={finding.path} kind={finding.kind}",
                file=sys.stderr,
            )
        return 1
    print("provider_surface_renderer: PASS providers=3 drift=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
