#!/usr/bin/env python3
"""Render deterministic Claude, Codex, and shared Stage 00 projections."""

from __future__ import annotations

import argparse
import errno
import hashlib
import json
import os
import pathlib
import posixpath
import re
import secrets
import sys
import stat
import tomllib
import urllib.parse
from collections.abc import Mapping, Sequence
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.lib.agent_governance.agent_governance_contract import (  # noqa: E402
    AgentGovernanceState,
    ContractLoadError,
    RoleRecord,
    SkillRecord,
    load_agent_governance,
    validate_contract_bundle,
    ContractBundle,
)


MARKER = "Generated by scripts/operations/provider_surface_renderer.py"
QUARANTINE_ROOT = ".provider-surface-quarantine"
MAX_GENERATED_PROJECTION_BYTES = 8 * 1024 * 1024
MAX_STATIC_POINTER_BYTES = 8 * 1024
SUPPORTED_PROVIDERS = ("claude", "codex")
INLINE_LINK = re.compile(
    r"(?P<prefix>!?\[[^\]\n]*\]\()(?P<destination><[^>\n]+>|[^\s)]+)"
    r"(?P<title>\s+(?:\"[^\"\n]*\"|'[^'\n]*'|\([^()\n]*\)))?(?P<suffix>\))"
)
REFERENCE_LINK = re.compile(
    r"(?m)^(?P<prefix>[ \t]{0,3}\[[^\]\n]+\]:[ \t]*)(?P<destination><[^>\n]+>|\S+)"
)


@dataclass(frozen=True)
class Catalog:
    roles: tuple[RoleRecord, ...]
    skills: tuple[SkillRecord, ...]

    @property
    def agents(self) -> tuple[RoleRecord, ...]:
        return self.roles

    @property
    def functions(self) -> tuple[SkillRecord, ...]:
        return self.skills


@dataclass(frozen=True, order=True)
class RenderRecord:
    provider: str
    path: pathlib.PurePosixPath
    content: bytes


@dataclass(frozen=True, order=True)
class Finding:
    path: pathlib.PurePosixPath
    kind: str


@dataclass(frozen=True)
class ProjectionIdentity:
    device: int
    inode: int
    size: int
    digest: str


def load_catalog(root: pathlib.Path) -> Catalog:
    state = load_agent_governance(root)
    findings = validate_contract_bundle(root, ContractBundle(state))
    if findings:
        raise ValueError("canonical Stage 00 sources are invalid")
    return Catalog(state.roles, state.skills)


def _body(text: str) -> str:
    if not text.startswith("---\n"):
        return text.strip() + "\n"
    boundary = text.find("\n---\n", 4)
    if boundary < 0:
        raise ValueError("unterminated canonical frontmatter")
    return text[boundary + 5 :].strip() + "\n"


def _rebase_destination(
    destination: str,
    source: pathlib.PurePosixPath,
    output: pathlib.PurePosixPath,
) -> str:
    bracketed = destination.startswith("<") and destination.endswith(">")
    raw = destination[1:-1] if bracketed else destination
    parsed = urllib.parse.urlsplit(raw)
    if (
        not parsed.path
        or raw.startswith(("#", "/", "//"))
        or parsed.scheme
        or parsed.netloc
    ):
        return destination
    target = posixpath.normpath(posixpath.join(source.parent.as_posix(), parsed.path))
    if target == ".." or target.startswith("../"):
        raise ValueError("canonical Markdown link escapes repository")
    path = posixpath.relpath(target, output.parent.as_posix())
    rebased = urllib.parse.urlunsplit(("", "", path, parsed.query, parsed.fragment))
    return f"<{rebased}>" if bracketed else rebased


def _rebase_links(
    text: str,
    source: pathlib.PurePosixPath,
    output: pathlib.PurePosixPath,
) -> str:
    def inline(match: re.Match[str]) -> str:
        destination = _rebase_destination(match.group("destination"), source, output)
        return f"{match.group('prefix')}{destination}{match.group('title') or ''}{match.group('suffix')}"

    def reference(match: re.Match[str]) -> str:
        destination = _rebase_destination(match.group("destination"), source, output)
        return f"{match.group('prefix')}{destination}"

    return REFERENCE_LINK.sub(reference, INLINE_LINK.sub(inline, text))


def _description(role: RoleRecord) -> str:
    return f"Canonical {role.scope} role for {role.agent_id}; owned by Stage 00."


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _selection(
    state: AgentGovernanceState, role: RoleRecord, provider: str
) -> Mapping[str, object]:
    profiles = state.registry.get("work_profiles")
    if not isinstance(profiles, dict):
        raise ValueError("provider work profiles are missing")
    profile = profiles.get(role.work_profile)
    selection = profile.get(provider) if isinstance(profile, dict) else None
    if not isinstance(selection, dict):
        raise ValueError(f"provider selection missing: {role.work_profile}/{provider}")
    return selection


def _permission(state: AgentGovernanceState, role: RoleRecord, provider: str) -> str:
    permissions = state.registry.get("permissions")
    profile = (
        permissions.get(role.permission_profile)
        if isinstance(permissions, dict)
        else None
    )
    value = profile.get(provider) if isinstance(profile, dict) else None
    if not isinstance(value, str):
        raise ValueError(
            f"provider permission missing: {role.permission_profile}/{provider}"
        )
    return value


def _marker(source: pathlib.PurePosixPath, *, comment: str = "html") -> str:
    text = f"{MARKER}; source: {source.as_posix()}"
    return f"<!-- {text} -->" if comment == "html" else f"# {text}"


def _shared_agent(role: RoleRecord, output: pathlib.PurePosixPath) -> bytes:
    body = _rebase_links(_body(role.source_text), role.source_path, output)
    return (
        "---\n"
        f"name: {_yaml_scalar(role.agent_id)}\n"
        f"description: {_yaml_scalar(_description(role))}\n"
        "---\n\n"
        f"{_marker(role.source_path)}\n\n{body}"
    ).encode()


def _claude_agent(
    state: AgentGovernanceState, role: RoleRecord, output: pathlib.PurePosixPath
) -> bytes:
    selection = _selection(state, role, "claude")
    tools = ["Read", "Grep", "Glob"]
    if role.permission_profile == "workspace-write":
        tools.extend(["Edit", "Write", "Bash"])
    lines = [
        "---",
        f"name: {_yaml_scalar(role.agent_id)}",
        f"description: {_yaml_scalar(_description(role))}",
        "tools:",
        *(f"- {_yaml_scalar(item)}" for item in tools),
        f"model: {_yaml_scalar(str(selection['model']))}",
    ]
    if selection.get("value") is not None:
        lines.append(f"effort: {_yaml_scalar(str(selection['value']))}")
    lines.extend(
        [
            f"permissionMode: {_yaml_scalar(_permission(state, role, 'claude'))}",
            "skills:",
            *(f"- {_yaml_scalar(item)}" for item in role.skill_ids),
            "---",
            "",
            _marker(role.source_path),
            "",
            _rebase_links(_body(role.source_text), role.source_path, output).rstrip(),
            "",
        ]
    )
    return "\n".join(lines).encode()


def _codex_agent(
    state: AgentGovernanceState, role: RoleRecord, output: pathlib.PurePosixPath
) -> bytes:
    selection = _selection(state, role, "codex")
    body = _rebase_links(_body(role.source_text), role.source_path, output)
    instructions = f"{_marker(role.source_path, comment='hash')}\n\n{body}".rstrip()
    values = {
        "name": role.agent_id,
        "description": _description(role),
        "developer_instructions": instructions,
        "model": selection["model"],
        "model_reasoning_effort": selection["value"],
        "sandbox_mode": _permission(state, role, "codex"),
    }
    return "".join(
        f"{key} = {json.dumps(value)}\n" for key, value in values.items()
    ).encode()


def _skill(skill: SkillRecord, output: pathlib.PurePosixPath) -> bytes:
    body = _rebase_links(_body(skill.source_text), skill.source_path, output)
    return (
        "---\n"
        f"name: {_yaml_scalar(skill.skill_id)}\n"
        f"description: {_yaml_scalar(f'Canonical {skill.scope} procedure for {skill.skill_id}; owned by {skill.owner_agent}.')}\n"
        "---\n\n"
        f"{_marker(skill.source_path)}\n\n{body}"
    ).encode()


def _pointer(
    title: str,
    source: pathlib.PurePosixPath,
    path: pathlib.PurePosixPath | None = None,
) -> bytes:
    # A projected README is an entrypoint document with a registered Stage 99
    # form, so it carries that form's frontmatter. Provider instruction files
    # such as CLAUDE.md stay provider-owned and frontmatter-free.
    envelope = ""
    if path is not None and path.name == "README.md":
        envelope = (
            "---\n"
            f'title: "{title}"\n'
            'version: "1.0.0"\n'
            'type: "common/runtime-governance-readme"\n'
            'status: "active"\n'
            'owner: "@buenhyden"\n'
            'updated: "2026-09-04"\n'
            'generated_by: "scripts/operations/provider_surface_renderer.py"\n'
            "---\n\n"
        )
    return f"{envelope}{_marker(source)}\n\n# {title}\n\nThis generated adapter routes to `{source}`.\n".encode()


def render_all(
    source_root: pathlib.Path,
    providers: Sequence[str] = SUPPORTED_PROVIDERS,
) -> tuple[RenderRecord, ...]:
    requested = tuple(providers)
    if requested != SUPPORTED_PROVIDERS:
        unsupported = sorted(set(requested) - set(SUPPORTED_PROVIDERS))
        if unsupported:
            raise ValueError(f"unsupported provider: {unsupported[0]}")
        raise ValueError("providers must be exactly claude and codex")
    state = load_agent_governance(source_root)
    bundle_findings = validate_contract_bundle(source_root, ContractBundle(state))
    if bundle_findings:
        raise ValueError("canonical Stage 00 sources are invalid")
    records: list[RenderRecord] = []
    providers_by_id = {item.provider_id: item for item in state.provider_records}
    for role in state.roles:
        shared_path = pathlib.PurePosixPath(
            state.compatibility.agent_pattern.format(agent_id=role.agent_id)
        )
        records.append(
            RenderRecord("shared", shared_path, _shared_agent(role, shared_path))
        )
        for provider_id in SUPPORTED_PROVIDERS:
            provider = providers_by_id[provider_id]
            native_path = pathlib.PurePosixPath(
                provider.agent_pattern.format(agent_id=role.agent_id)
            )
            content = (
                _claude_agent(state, role, native_path)
                if provider_id == "claude"
                else _codex_agent(state, role, native_path)
            )
            records.append(RenderRecord(provider_id, native_path, content))
    for skill in state.skills:
        shared_path = pathlib.PurePosixPath(
            state.compatibility.skill_pattern.format(skill_id=skill.skill_id)
        )
        records.append(RenderRecord("shared", shared_path, _skill(skill, shared_path)))
        seen = {shared_path}
        for provider_id in SUPPORTED_PROVIDERS:
            provider = providers_by_id[provider_id]
            native_path = pathlib.PurePosixPath(
                provider.skill_pattern.format(skill_id=skill.skill_id)
            )
            if native_path in seen:
                continue
            seen.add(native_path)
            records.append(
                RenderRecord(provider_id, native_path, _skill(skill, native_path))
            )
    projections = state.registry.get("projections")
    if not isinstance(projections, list):
        raise ValueError("projections must be a registered list")
    for projection in projections:
        if not isinstance(projection, dict):
            raise ValueError("projection rows must be mappings")
        provider = str(projection["provider_id"])
        path = pathlib.PurePosixPath(str(projection["path"]))
        source = pathlib.PurePosixPath(str(projection["source"]))
        title = (
            "Shared Runtime Route"
            if provider == "shared"
            else f"{provider.title()} Runtime Route"
        )
        records.append(RenderRecord(provider, path, _pointer(title, source, path)))
    return tuple(sorted(records, key=lambda item: item.path.as_posix()))


def expected_native_projection(root: pathlib.Path) -> Mapping[pathlib.Path, bytes]:
    return {
        pathlib.Path(item.path.as_posix()): item.content for item in render_all(root)
    }


def expected_projection(
    root: pathlib.Path, provider: str
) -> Mapping[pathlib.Path, bytes]:
    aliases = {
        "agents-md": "shared",
        "shared": "shared",
        "claude": "claude",
        "codex": "codex",
    }
    selected = aliases.get(provider)
    if selected is None:
        raise ValueError(f"unsupported provider: {provider}")
    return {
        pathlib.Path(item.path.as_posix()): item.content
        for item in render_all(root)
        if item.provider == selected
    }


def _managed_roots(state: AgentGovernanceState) -> tuple[pathlib.PurePosixPath, ...]:
    values = state.registry.get("generated_roots")
    if not isinstance(values, list) or any(
        not isinstance(item, str) for item in values
    ):
        raise ValueError("generated_roots must be a string list")
    roots = tuple(pathlib.PurePosixPath(item) for item in values)
    if len(roots) != len(set(roots)) or any(
        item.is_absolute()
        or len(item.parts) < 2
        or item.parts[0] not in {".agents", ".claude", ".codex"}
        or any(part in {"", ".", ".."} for part in item.parts)
        for item in roots
    ):
        raise ValueError("generated_roots contain an unsafe path")
    return roots


def _projection_namespaces(
    state: AgentGovernanceState,
) -> tuple[pathlib.PurePosixPath, ...]:
    patterns = (
        state.compatibility.agent_pattern,
        state.compatibility.skill_pattern,
        *(record.agent_pattern for record in state.provider_records),
        *(record.skill_pattern for record in state.provider_records),
    )
    return tuple(
        sorted(
            {
                pathlib.PurePosixPath(pathlib.PurePosixPath(pattern).parts[0])
                for pattern in patterns
            }
        )
    )


def _current_managed_files(
    root: pathlib.Path, state: AgentGovernanceState
) -> tuple[pathlib.PurePosixPath, ...]:
    result: list[pathlib.PurePosixPath] = []
    for relative in _managed_roots(state):
        directory = root / relative
        try:
            metadata = directory.lstat()
        except FileNotFoundError:
            continue
        if stat.S_ISLNK(metadata.st_mode):
            raise ValueError(f"managed root is a symlink: {relative}")
        if not stat.S_ISDIR(metadata.st_mode):
            raise ValueError(f"managed root is not a directory: {relative}")
        descriptor = _open_directory_descriptor(root, relative.parts)
        try:
            _scan_managed_directory(descriptor, relative, result)
        finally:
            os.close(descriptor)
    return tuple(sorted(set(result)))


def _directory_flags() -> int:
    return os.O_RDONLY | os.O_DIRECTORY | getattr(os, "O_NOFOLLOW", 0)


def _open_directory_descriptor(
    root: pathlib.Path,
    parts: Sequence[str],
    *,
    create: bool = False,
    create_mode: int = 0o755,
) -> int:
    try:
        descriptor = os.open(root, _directory_flags())
    except OSError as error:
        raise ValueError("projection root is not a stable directory") from error
    try:
        for part in parts:
            if part in {"", ".", ".."}:
                raise ValueError("unsafe projection directory")
            try:
                child = os.open(part, _directory_flags(), dir_fd=descriptor)
            except FileNotFoundError:
                if not create:
                    raise
                os.mkdir(part, mode=create_mode, dir_fd=descriptor)
                child = os.open(part, _directory_flags(), dir_fd=descriptor)
            os.close(descriptor)
            descriptor = child
        return descriptor
    except BaseException:
        os.close(descriptor)
        raise


def _open_parent_descriptor(
    root: pathlib.Path,
    relative: pathlib.PurePosixPath,
    *,
    create: bool = False,
) -> int:
    if relative.is_absolute() or any(
        part in {"", ".", ".."} for part in relative.parts
    ):
        raise ValueError(f"unsafe projection path: {relative}")
    try:
        return _open_directory_descriptor(root, relative.parent.parts, create=create)
    except (OSError, ValueError) as error:
        raise ValueError(
            f"projection parent changed or is unsafe: {relative}"
        ) from error


def _scan_managed_directory(
    descriptor: int,
    relative: pathlib.PurePosixPath,
    result: list[pathlib.PurePosixPath],
) -> None:
    try:
        entries = tuple(os.scandir(descriptor))
    except OSError as error:
        raise ValueError(
            f"managed root changed during traversal: {relative}"
        ) from error
    for entry in sorted(entries, key=lambda item: item.name):
        child_relative = relative / entry.name
        try:
            metadata = entry.stat(follow_symlinks=False)
        except OSError as error:
            raise ValueError(
                f"managed projection changed during traversal: {child_relative}"
            ) from error
        if stat.S_ISLNK(metadata.st_mode):
            raise ValueError(f"managed projection is a symlink: {child_relative}")
        if stat.S_ISDIR(metadata.st_mode):
            try:
                child = os.open(entry.name, _directory_flags(), dir_fd=descriptor)
            except OSError as error:
                raise ValueError(
                    f"managed directory changed during traversal: {child_relative}"
                ) from error
            try:
                _scan_managed_directory(child, child_relative, result)
            finally:
                os.close(child)
        elif stat.S_ISREG(metadata.st_mode):
            result.append(child_relative)
        else:
            raise ValueError(f"managed projection is not regular: {child_relative}")


def _generated_marker_source(candidate: bytes) -> pathlib.PurePosixPath | None:
    try:
        text = candidate.decode("ascii")
    except UnicodeDecodeError:
        return None
    if text.startswith("<!-- ") and text.endswith(" -->"):
        text = text[5:-4]
    elif text.startswith("# "):
        text = text[2:]
    elif text.startswith("<!-- ") or text.endswith(" -->"):
        return None
    marker = re.fullmatch(
        rf"{re.escape(MARKER)}; source: (?P<source>[^<>\s]+)",
        text,
    )
    if marker is None:
        return None
    try:
        source = pathlib.PurePosixPath(marker.group("source"))
    except ValueError:
        return None
    if not (
        not source.is_absolute()
        and ".." not in source.parts
        and source.parts[:2] == ("docs", "00.agent-governance")
    ):
        return None
    return source


def _markdown_marker_candidate(payload: bytes) -> bytes:
    lines = payload[:MAX_STATIC_POINTER_BYTES].splitlines()
    candidate = lines[0] if lines else b""
    if candidate == b"---":
        try:
            boundary = lines[1:].index(b"---") + 1
        except ValueError:
            return b""
        remainder = lines[boundary + 1 :]
        candidate = next((line for line in remainder if line.strip()), b"")
    return candidate


def _is_codex_agent_projection(payload: bytes) -> bool:
    try:
        document = tomllib.loads(payload.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError):
        return False
    required = {
        "name",
        "description",
        "developer_instructions",
        "model",
        "model_reasoning_effort",
        "sandbox_mode",
    }
    if set(document) != required or any(
        not isinstance(document[key], str) for key in required
    ):
        return False
    name = document["name"]
    if re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name) is None:
        return False
    if (
        re.fullmatch(
            rf"Canonical .+ role for {re.escape(name)}; owned by Stage 00\.",
            document["description"],
            flags=re.DOTALL,
        )
        is None
    ):
        return False
    instructions = document["developer_instructions"].splitlines()
    marker = instructions[0].encode("ascii", errors="strict") if instructions else b""
    source = _generated_marker_source(marker)
    return source == pathlib.PurePosixPath(f"docs/00.agent-governance/roles/{name}.md")


def _is_generated(payload: bytes) -> bool:
    if _generated_marker_source(_markdown_marker_candidate(payload)) is not None:
        return True
    try:
        return _is_codex_agent_projection(payload)
    except UnicodeEncodeError:
        return False


def _read_projection_prefix_at(
    parent_descriptor: int,
    relative: pathlib.PurePosixPath,
    expected: os.stat_result,
) -> bytes:
    descriptor = os.open(
        relative.name,
        os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | os.O_NONBLOCK,
        dir_fd=parent_descriptor,
    )
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode):
            raise ValueError(f"projection is not a regular file: {relative}")
        if (
            before.st_dev,
            before.st_ino,
            before.st_size,
            before.st_mtime_ns,
            before.st_ctime_ns,
        ) != (
            expected.st_dev,
            expected.st_ino,
            expected.st_size,
            expected.st_mtime_ns,
            expected.st_ctime_ns,
        ):
            raise ValueError(f"projection changed before prefix read: {relative}")
        payload = os.read(descriptor, MAX_STATIC_POINTER_BYTES)
        after = os.fstat(descriptor)
        if (
            before.st_dev,
            before.st_ino,
            before.st_size,
            before.st_mtime_ns,
            before.st_ctime_ns,
        ) != (
            after.st_dev,
            after.st_ino,
            after.st_size,
            after.st_mtime_ns,
            after.st_ctime_ns,
        ):
            raise ValueError(f"projection changed during prefix read: {relative}")
        return payload
    finally:
        os.close(descriptor)


def _current_static_generated_files(
    root: pathlib.Path, state: AgentGovernanceState
) -> tuple[pathlib.PurePosixPath, ...]:
    result: list[pathlib.PurePosixPath] = []
    for namespace in _projection_namespaces(state):
        try:
            descriptor = _open_directory_descriptor(root.absolute(), namespace.parts)
        except OSError as error:
            raise ValueError(
                f"projection namespace changed or is a symlink: {namespace}"
            ) from error
        try:
            entries = tuple(os.scandir(descriptor))
            for entry in sorted(entries, key=lambda item: item.name):
                relative = namespace / entry.name
                try:
                    metadata = entry.stat(follow_symlinks=False)
                except OSError as error:
                    raise ValueError(
                        f"projection namespace changed during traversal: {relative}"
                    ) from error
                if not stat.S_ISREG(metadata.st_mode):
                    continue
                if metadata.st_size > MAX_STATIC_POINTER_BYTES:
                    try:
                        prefix = _read_projection_prefix_at(
                            descriptor, relative, metadata
                        )
                    except (OSError, ValueError) as error:
                        raise ValueError(
                            f"projection namespace changed during prefix read: {relative}"
                        ) from error
                    if _is_generated(prefix):
                        result.append(relative)
                    continue
                try:
                    _owned_projection_identity_at(descriptor, relative)
                except (OSError, ValueError):
                    continue
                result.append(relative)
        finally:
            os.close(descriptor)
    return tuple(result)


def _safe_projection_path(
    root: pathlib.Path, relative: pathlib.PurePosixPath
) -> pathlib.Path:
    if relative.is_absolute() or any(
        part in {"", ".", ".."} for part in relative.parts
    ):
        raise ValueError(f"unsafe projection path: {relative}")
    current = root
    for part in relative.parent.parts:
        current = current / part
        metadata = current.lstat()
        if stat.S_ISLNK(metadata.st_mode):
            raise ValueError(f"projection parent is a symlink: {relative}")
        if not stat.S_ISDIR(metadata.st_mode):
            raise ValueError(f"projection parent is not a directory: {relative}")
    return root / relative


def _owned_projection_identity(
    root: pathlib.Path, relative: pathlib.PurePosixPath
) -> ProjectionIdentity:
    parent_descriptor = _open_parent_descriptor(root.absolute(), relative)
    try:
        return _owned_projection_identity_at(parent_descriptor, relative)
    finally:
        os.close(parent_descriptor)


def _owned_projection_identity_at(
    parent_descriptor: int, relative: pathlib.PurePosixPath
) -> ProjectionIdentity:
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | os.O_NONBLOCK
    descriptor = os.open(relative.name, flags, dir_fd=parent_descriptor)
    try:
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode):
            raise ValueError(f"unowned file in generated root: {relative}")
        if metadata.st_size > MAX_GENERATED_PROJECTION_BYTES:
            raise ValueError(f"generated projection is oversized: {relative}")
        payload = bytearray()
        while True:
            chunk = os.read(descriptor, 65536)
            if not chunk:
                break
            payload.extend(chunk)
            if len(payload) > MAX_GENERATED_PROJECTION_BYTES:
                raise ValueError(f"generated projection is oversized: {relative}")
        if not _is_generated(bytes(payload)):
            raise ValueError(f"unowned file in generated root: {relative}")
        return ProjectionIdentity(
            device=metadata.st_dev,
            inode=metadata.st_ino,
            size=metadata.st_size,
            digest=hashlib.sha256(payload).hexdigest(),
        )
    finally:
        os.close(descriptor)


def _quarantine_owned_projection(
    root: pathlib.Path,
    relative: pathlib.PurePosixPath,
    expected: ProjectionIdentity,
) -> pathlib.PurePosixPath:
    quarantine_descriptor = -1
    try:
        parent_descriptor = _open_parent_descriptor(root.absolute(), relative)
    except ValueError as error:
        raise ValueError(
            f"managed projection changed before deletion: {relative}"
        ) from error
    try:
        try:
            actual = _owned_projection_identity_at(parent_descriptor, relative)
            metadata = os.stat(
                relative.name, dir_fd=parent_descriptor, follow_symlinks=False
            )
        except (OSError, ValueError) as error:
            raise ValueError(
                f"managed projection changed before deletion: {relative}"
            ) from error
        if actual != expected or (
            metadata.st_dev,
            metadata.st_ino,
            metadata.st_size,
        ) != (expected.device, expected.inode, expected.size):
            raise ValueError(f"managed projection changed before deletion: {relative}")
        try:
            quarantine_descriptor = _open_directory_descriptor(
                root.absolute(), (QUARANTINE_ROOT,), create=True, create_mode=0o700
            )
            quarantine_metadata = os.fstat(quarantine_descriptor)
        except OSError as error:
            raise ValueError("isolated projection quarantine is unavailable") from error
        if (
            quarantine_metadata.st_uid != os.geteuid()
            or stat.S_IMODE(quarantine_metadata.st_mode) & 0o077
        ):
            raise ValueError(
                "isolated projection quarantine has unsafe ownership or mode"
            )
        quarantine = f"projection.delete-{secrets.token_hex(12)}"
        os.rename(
            relative.name,
            quarantine,
            src_dir_fd=parent_descriptor,
            dst_dir_fd=quarantine_descriptor,
        )
        quarantined = pathlib.PurePosixPath(quarantine)
        try:
            moved = _owned_projection_identity_at(quarantine_descriptor, quarantined)
            if moved != expected:
                raise ValueError("projection identity changed during deletion")
            confirmed = _owned_projection_identity_at(
                quarantine_descriptor, quarantined
            )
            if confirmed != expected:
                raise ValueError(
                    "projection identity changed after quarantine validation"
                )
            return pathlib.PurePosixPath(QUARANTINE_ROOT) / quarantine
        except (OSError, ValueError) as error:
            try:
                os.link(
                    quarantine,
                    relative.name,
                    src_dir_fd=quarantine_descriptor,
                    dst_dir_fd=parent_descriptor,
                    follow_symlinks=False,
                )
            except FileExistsError:
                pass
            except OSError:
                pass
            raise ValueError(
                "managed projection changed and was retained in isolated quarantine: "
                f"{QUARANTINE_ROOT}/{quarantine}"
            ) from error
    finally:
        if quarantine_descriptor >= 0:
            os.close(quarantine_descriptor)
        os.close(parent_descriptor)


def _pending_quarantine_paths(root: pathlib.Path) -> tuple[pathlib.PurePosixPath, ...]:
    try:
        descriptor = _open_directory_descriptor(root.absolute(), (QUARANTINE_ROOT,))
    except FileNotFoundError:
        return ()
    try:
        metadata = os.fstat(descriptor)
        if metadata.st_uid != os.geteuid() or stat.S_IMODE(metadata.st_mode) & 0o077:
            raise ValueError(
                "isolated projection quarantine has unsafe ownership or mode"
            )
        result: list[pathlib.PurePosixPath] = []
        for entry in os.scandir(descriptor):
            entry_metadata = entry.stat(follow_symlinks=False)
            if re.fullmatch(
                r"projection\.delete-[a-f0-9]{24}", entry.name
            ) is None or not stat.S_ISREG(entry_metadata.st_mode):
                raise ValueError(
                    "isolated projection quarantine contains unsafe content"
                )
            result.append(pathlib.PurePosixPath(QUARANTINE_ROOT) / entry.name)
        return tuple(sorted(result))
    finally:
        os.close(descriptor)


def _remove_empty_quarantine(root: pathlib.Path) -> None:
    descriptor = _open_directory_descriptor(root.absolute(), ())
    try:
        try:
            os.rmdir(QUARANTINE_ROOT, dir_fd=descriptor)
        except FileNotFoundError:
            return
        except OSError as error:
            if error.errno in {errno.EEXIST, errno.ENOTEMPTY}:
                return
            raise ValueError("isolated projection quarantine is unsafe") from error
    finally:
        os.close(descriptor)


def _cleanup_empty_directories_at(
    descriptor: int, relative: pathlib.PurePosixPath
) -> None:
    try:
        entries = tuple(os.scandir(descriptor))
    except OSError as error:
        raise ValueError(f"managed root changed during cleanup: {relative}") from error
    for entry in sorted(entries, key=lambda item: item.name):
        child_relative = relative / entry.name
        try:
            metadata = entry.stat(follow_symlinks=False)
        except OSError as error:
            raise ValueError(
                f"managed directory changed during cleanup: {child_relative}"
            ) from error
        if stat.S_ISLNK(metadata.st_mode):
            raise ValueError(
                f"managed root contains a replacement symlink: {child_relative}"
            )
        if not stat.S_ISDIR(metadata.st_mode):
            continue
        try:
            child = os.open(entry.name, _directory_flags(), dir_fd=descriptor)
        except OSError as error:
            raise ValueError(
                f"managed directory changed during cleanup: {child_relative}"
            ) from error
        try:
            opened = os.fstat(child)
            _cleanup_empty_directories_at(child, child_relative)
        finally:
            os.close(child)
        try:
            current = os.stat(entry.name, dir_fd=descriptor, follow_symlinks=False)
        except OSError as error:
            raise ValueError(
                f"managed directory changed during cleanup: {child_relative}"
            ) from error
        if (current.st_dev, current.st_ino) != (opened.st_dev, opened.st_ino):
            raise ValueError(
                f"managed directory changed during cleanup: {child_relative}"
            )
        try:
            os.rmdir(entry.name, dir_fd=descriptor)
        except OSError:
            pass


def _cleanup_empty_managed_directories(
    root: pathlib.Path, state: AgentGovernanceState
) -> None:
    for managed_root in _managed_roots(state):
        try:
            descriptor = _open_directory_descriptor(root, managed_root.parts)
        except OSError as error:
            raise ValueError(
                f"managed root changed or is a symlink: {managed_root}"
            ) from error
        try:
            _cleanup_empty_directories_at(descriptor, managed_root)
        finally:
            os.close(descriptor)


def _read_projection_bytes(
    root: pathlib.Path, relative: pathlib.PurePosixPath
) -> bytes:
    parent_descriptor = _open_parent_descriptor(root.absolute(), relative)
    descriptor = -1
    try:
        descriptor = os.open(
            relative.name,
            os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | os.O_NONBLOCK,
            dir_fd=parent_descriptor,
        )
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode):
            raise ValueError(f"projection is not a regular file: {relative}")
        if before.st_size > MAX_GENERATED_PROJECTION_BYTES:
            raise ValueError(f"projection is oversized: {relative}")
        payload = bytearray()
        while True:
            chunk = os.read(descriptor, 65536)
            if not chunk:
                break
            payload.extend(chunk)
            if len(payload) > MAX_GENERATED_PROJECTION_BYTES:
                raise ValueError(f"projection is oversized: {relative}")
        after = os.fstat(descriptor)
        if (
            before.st_dev,
            before.st_ino,
            before.st_size,
            before.st_mtime_ns,
            before.st_ctime_ns,
        ) != (
            after.st_dev,
            after.st_ino,
            after.st_size,
            after.st_mtime_ns,
            after.st_ctime_ns,
        ):
            raise ValueError(f"projection changed while reading: {relative}")
        return bytes(payload)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        os.close(parent_descriptor)


def find_native_projection_drift(root: pathlib.Path) -> list[Finding]:
    root = root.absolute()
    state = load_agent_governance(root)
    expected = expected_native_projection(root)
    findings = [
        Finding(path, "pending-cleanup") for path in _pending_quarantine_paths(root)
    ]
    for path, content in expected.items():
        relative = pathlib.PurePosixPath(path.as_posix())
        try:
            actual = _read_projection_bytes(root, relative)
        except FileNotFoundError:
            findings.append(Finding(relative, "missing"))
        except (OSError, ValueError):
            findings.append(Finding(relative, "unsafe"))
        else:
            if actual != content:
                findings.append(Finding(relative, "drift"))
    expected_paths = {pathlib.PurePosixPath(path.as_posix()) for path in expected}
    current_generated = set(_current_managed_files(root, state))
    current_generated.update(_current_static_generated_files(root, state))
    for path in sorted(current_generated):
        if path not in expected_paths:
            try:
                payload = _read_projection_bytes(root, path)
            except (OSError, ValueError):
                kind = "unsafe"
            else:
                kind = "stale-generated" if _is_generated(payload) else "unowned"
            findings.append(Finding(path, kind))
    return sorted(set(findings))


def _atomic_write(
    root: pathlib.Path, relative: pathlib.PurePosixPath, content: bytes
) -> None:
    parent_descriptor = _open_parent_descriptor(root.absolute(), relative, create=True)
    temporary = f".{relative.name}.{secrets.token_hex(12)}"
    descriptor = -1
    try:
        try:
            metadata = os.stat(
                relative.name, dir_fd=parent_descriptor, follow_symlinks=False
            )
        except FileNotFoundError:
            metadata = None
        if metadata is not None and not stat.S_ISREG(metadata.st_mode):
            raise ValueError(f"projection target is unsafe: {relative}")
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
            dir_fd=parent_descriptor,
        )
        with os.fdopen(descriptor, "wb") as handle:
            descriptor = -1
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(
            temporary,
            relative.name,
            src_dir_fd=parent_descriptor,
            dst_dir_fd=parent_descriptor,
        )
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            os.unlink(temporary, dir_fd=parent_descriptor)
        except FileNotFoundError:
            pass
        os.close(parent_descriptor)


def write_native_projection(root: pathlib.Path) -> None:
    root = root.absolute()
    state = load_agent_governance(root)
    expected = expected_native_projection(root)
    pending = _pending_quarantine_paths(root)
    if pending:
        rendered = ", ".join(path.as_posix() for path in pending)
        raise ValueError(
            f"quarantined generated projections require manual cleanup: {rendered}"
        )
    expected_paths = {pathlib.PurePosixPath(path.as_posix()) for path in expected}
    stale: list[tuple[pathlib.PurePosixPath, ProjectionIdentity]] = []
    current_generated = set(_current_managed_files(root, state))
    current_generated.update(_current_static_generated_files(root, state))
    for path in sorted(current_generated):
        if path in expected_paths:
            continue
        stale.append((path, _owned_projection_identity(root, path)))
    quarantined = [
        _quarantine_owned_projection(root, path, identity) for path, identity in stale
    ]
    if quarantined:
        rendered = ", ".join(path.as_posix() for path in quarantined)
        raise ValueError(
            f"stale generated projections quarantined; manual cleanup required: {rendered}"
        )
    for path, content in expected.items():
        _atomic_write(root, pathlib.PurePosixPath(path.as_posix()), content)
    _cleanup_empty_managed_directories(root, state)
    _remove_empty_quarantine(root)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=pathlib.Path, default=ROOT)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        if args.write:
            write_native_projection(args.root)
        findings = find_native_projection_drift(args.root)
    except (ContractLoadError, OSError, ValueError) as error:
        print(f"provider_surface_renderer: ERROR {error}", file=sys.stderr)
        return 1
    if findings:
        for finding in findings:
            print(f"{finding.kind}: {finding.path}", file=sys.stderr)
        return 1
    print("provider_surface_renderer: PASS providers=2 drift=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
