#!/usr/bin/env bash
# Generated by scripts/operations/provider_surface_renderer.py; Gemini native-to-semantic event adapter.
set -euo pipefail

if [[ "${HY_HOME_GEMINI_HOOK_ACTIVE:-}" == "1" ]]; then
  printf '{}\n'
  exit 0
fi
export HY_HOME_GEMINI_HOOK_ACTIVE=1
PROJECT_DIR="${GEMINI_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
NATIVE_EVENT="${1:-}"
case "$NATIVE_EVENT" in
  AfterTool) SEMANTIC_EVENT=PostToolUse ;;
  PreCompress) SEMANTIC_EVENT=PreCompact ;;
  BeforeTool) SEMANTIC_EVENT=PreToolUse ;;
  SessionEnd) SEMANTIC_EVENT=SessionEnd ;;
  SessionStart) SEMANTIC_EVENT=SessionStart ;;
  AfterAgent) SEMANTIC_EVENT=Stop ;;
  BeforeAgent) SEMANTIC_EVENT=UserPromptSubmit ;;
  *) printf 'Unsupported Gemini hook event.\n' >&2; exit 2 ;;
esac
exec bash "$PROJECT_DIR/scripts/hooks/agent-event-hook.sh" "$SEMANTIC_EVENT"
