x-tier-label: &tier-label
  hy-home.tier: admin

volumes:
  surrealdb-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_MANAGEMENT_DIR}/surrealdb/data

services:
  surrealdb:
    profiles:
      - admin
      - notebook
      - surrealdb
    extends:
      file: ../../../common-optimizations.yml
      service: template-stateful-db-med
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SURREALDB_USERNAME: ${SURREALDB_USERNAME}
    expose:
      - '8000'
    ports:
      - '127.0.0.1:${SURREALDB_HOST_PORT:-8000}:8000'
    volumes:
      - surrealdb-data:/mydata
    labels:
      <<: *tier-label
    networks:
      infra_net:
        ipv4_address: 172.19.0.122
    healthcheck:
      test: [ "CMD", "/usr/local/bin/surreal", "isready", "--conn", "http://127.0.0.1:8000" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    secrets:
      - surreal_db_password
