name: Build and Run Service in Docker
description: >
  Build and run the main application service from the current repository using
  Docker, without relying on hard-coded paths.

triggers:
  - user_request: "run the app in docker"
  - user_request: "build and run service container"

assumptions:
  - The workspace root is the active project directory.
  - A suitable Dockerfile exists in the repository.
  - The user’s environment has Docker installed and running.

steps:
  - name: Discover Dockerfile
    action: analyze_repository
    description: >
      Locate candidate Dockerfiles under the current workspace root. If multiple
      Dockerfiles exist, ask the user which one to treat as the main entrypoint.

  - name: Select build context
    action: decide_context
    description: >
      Infer the build context directory as the folder containing the chosen
      Dockerfile, or the repository root if appropriate. Avoid using absolute
      host paths.

  - name: Propose image name
    action: plan_image
    description: >
      Propose a short, lowercase image name derived from the repository folder
      (for example, repo name) and an explicit tag such as `local` or a date
      tag. Avoid using `latest` unless requested.

  - name: Build image
    action: shell_command
    command_template: >
      docker build -t {{ image_name }}:{{ image_tag }} {{ build_context }}
    notes: >
      Ensure the command uses a relative build context, not an absolute path. If
      the user requires build arguments or target stages, ask for details.

  - name: Plan container runtime
    action: plan_runtime
    description: >
      Decide on container runtime options such as environment variables, port
      mappings, and volumes. Only expose ports that are needed and prefer
      localhost bindings.

  - name: Run container
    action: shell_command
    command_template: >
      docker run --rm -p {{ host_port }}:{{ container_port }} {{ env_flags }} {{
      volume_flags }} {{ image_name }}:{{ image_tag }}
    notes: >
      Document the chosen ports and environment variables in the response.
      Explain how the user can stop the container and rerun it later.

  - name: Provide usage summary
    action: summarize
    description: >
      Present a short summary with the exact build and run commands and explain
      how to adapt them for different environments or ports.
