name: Dev Container Agent Workflow
description: >
  Build and launch a Dev Container using Docker, then run the agent or
  development tools inside that container, without binding to a fixed host path.

triggers:
  - user_request: "run agent in devcontainer"
  - user_request: "open project in dev container"

assumptions:
  - A `.devcontainer` configuration may exist or be created for the project.
  - Docker is available on the host.

steps:
  - name: Discover or create devcontainer config
    action: analyze_repository
    description: >
      Look for a `.devcontainer` folder containing `devcontainer.json` or
      related configuration. If none is found, propose a minimal configuration
      compatible with the project’s language and toolchain.

  - name: Ensure path-agnostic mounts
    action: adjust_mounts
    description: >
      Configure workspace mounting using relative paths from the repository root
      so the same Dev Container configuration works on any machine.

  - name: Build and start Dev Container
    action: shell_command
    command_template: >
      devcontainer up --workspace-folder .
    notes: >
      Explain any prerequisites, such as installing the Dev Container CLI.

  - name: Execute agent or tools inside container
    action: shell_command
    command_template: >
      devcontainer exec --workspace-folder . {{ agent_command }}
    notes: >
      Use this to run agents, CLIs, or scripts inside the container, keeping
      host environment clean.

  - name: Document usage
    action: summarize
    description: >
      Provide a short guide describing how to rebuild, reopen, and use the Dev
      Container, including common commands for running the agent inside it.
