name: Sandboxed Code Execution in Docker
description: >
  Run potentially unsafe or experimental code inside an isolated Docker
  container with controlled network and filesystem access.

triggers:
  - user_request: "run this code safely"
  - user_request: "sandbox this script in docker"

assumptions:
  - Docker is installed and supports basic networking options.
  - The code to run is located somewhere under the current workspace root.

steps:
  - name: Package code for container
    action: analyze_repository
    description: >
      Identify the minimal set of files needed to run the code and avoid
      mounting the entire repository if not required.

  - name: Build sandbox image
    action: shell_command
    command_template: >
      docker build -t {{ sandbox_image_name }} -f {{ sandbox_dockerfile }} {{
      build_context }}
    notes: >
      Use a minimal base image and install only the dependencies required for
      the given script or project.

  - name: Define isolation options
    action: plan_runtime
    description: >
      Configure the container with restricted network access (for example, no
      outbound network by default) and minimal capabilities, only adding more if
      the user explicitly approves.

  - name: Run code in sandbox
    action: shell_command
    command_template: >
      docker run --rm {{ security_flags }} {{ volume_flags }} {{
      sandbox_image_name }} {{ entrypoint_or_command }}
    notes: >
      Explain to the user how isolation is enforced and what limitations apply
      inside the sandbox.

  - name: Report results
    action: summarize
    description: >
      Present the output or logs from the sandboxed execution and describe how
      the user can repeat or adjust the run with different inputs or
      constraints.
