x-tier-label: &tier-label
  hy-home.tier: auth

volumes:
  oauth2-proxy-valkey-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_AUTH_DIR}/valkey

services:
  oauth2-proxy:
    profiles:
      - core
      - auth
      - dev
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-readonly-med
    # image: quay.io/oauth2-proxy/oauth2-proxy:v7.14.2
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: oauth2-proxy
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/rootCA.pem
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://mng-valkey:6379
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://keycloak.${DEFAULT_URL}/realms/hy-home.realm
      - OAUTH2_PROXY_REDIRECT_URL=https://auth.${DEFAULT_URL}/oauth2/callback
      - OAUTH2_PROXY_COOKIE_DOMAINS=.${DEFAULT_URL}
      - OAUTH2_PROXY_WHITELIST_DOMAINS=*.${DEFAULT_URL}
    volumes:
      - ./config/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg:ro
      - ../../../secrets/certs/rootCA.pem:/etc/ssl/certs/rootCA.pem:ro
    secrets:
      - mng_valkey_password
      - oauth2_proxy_client_secret
      - oauth2_proxy_cookie_secret
    labels:
      <<: *tier-label
      traefik.enable: 'true'
      traefik.http.routers.oauth2-proxy.rule: Host(`auth.${DEFAULT_URL}`) && PathPrefix(`/oauth2`)
      traefik.docker.network: infra_net
      traefik.http.routers.oauth2-proxy.entrypoints: websecure
      traefik.http.routers.oauth2-proxy.service: oauth2-proxy-svc
      traefik.http.routers.oauth2-proxy.tls: 'true'
      traefik.http.routers.oauth2-proxy.middlewares: gateway-standard-chain@file
      traefik.http.services.oauth2-proxy-svc.loadbalancer.server.port: ${OAUTH2_PROXY_PORT:-4180}
    networks:
      infra_net:
        ipv4_address: 172.19.0.4
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -qO- http://127.0.0.1:${OAUTH2_PROXY_PORT:-4180}/ping >/dev/null 2>&1 || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    extra_hosts:
      - 'keycloak.${DEFAULT_URL}:host-gateway'
      - 'auth.${DEFAULT_URL}:host-gateway'
