name: Greeting

on:
  pull_request:
    branches: [main]
    types: [opened]
  issues:
    types: [opened]

permissions: {}

jobs:
  issue-greeting:
    if: github.event_name == 'issues'
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Greet first issue
        uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message:
            "Welcome to the project! Thank you for opening your first issue. We
            will review it shortly."

  pull-request-greeting:
    if: github.event_name == 'pull_request'
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Greet first pull request
        uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          pr_message:
            "Welcome to the project! Thank you for your first Pull Request.
            We'll review your changes as soon as possible."
